export const COPERNICUS_CONTRIBUTING_MISSIONS = 'CCM';

const CCM_ROLES = {
  COPERNICUS_SERVICES_CCM: 'copernicus-services-ccm',
  UNION_INST_CCM: 'union-inst-ccm',
  UNION_RESEARCH_PROJECTS_SPACE_CCM: 'union-research-projects-space-ccm',
  UNION_RESEARCH_PROJECTS_NON_SPACE_CCM: 'union-research-projects-non-space-ccm',
  PUBLIC_AUTH_CCM: 'public-auth-ccm',
  INT_ORG_NGO_CCM: 'int-org-ngo-ccm',
  PUBLIC_CCM: 'public-ccm',
  COPERNICUS_OPERATORS_CCM: 'copernicus-operators-ccm',
};

const VHR_COMMON_ACCESS_RIGHTS = {
  DOWNLOAD_PRODUCT_ROLES: [
    CCM_ROLES.COPERNICUS_SERVICES_CCM,
    CCM_ROLES.UNION_INST_CCM,
    CCM_ROLES.UNION_RESEARCH_PROJECTS_SPACE_CCM,
    CCM_ROLES.UNION_RESEARCH_PROJECTS_NON_SPACE_CCM,
    CCM_ROLES.PUBLIC_AUTH_CCM,
  ],
};

const VHR_COPERNICUS_SERVICES_ONLY_ACCESS_RIGHTS = {
  DOWNLOAD_PRODUCT_ROLES: [CCM_ROLES.COPERNICUS_SERVICES_CCM],
};

const PARTIAL_2_ACCESS_RIGHTS = {
  DOWNLOAD_PRODUCT_ROLES: [
    CCM_ROLES.COPERNICUS_SERVICES_CCM,
    CCM_ROLES.UNION_INST_CCM,
    CCM_ROLES.UNION_RESEARCH_PROJECTS_SPACE_CCM,
    CCM_ROLES.PUBLIC_AUTH_CCM,
  ],
};

const COP_DEM_PARTIAL_ACCESS_RIGHTS = {
  DOWNLOAD_PRODUCT_ROLES: [
    CCM_ROLES.COPERNICUS_SERVICES_CCM,
    CCM_ROLES.UNION_INST_CCM,
    CCM_ROLES.UNION_RESEARCH_PROJECTS_SPACE_CCM,
    CCM_ROLES.UNION_RESEARCH_PROJECTS_NON_SPACE_CCM,
    CCM_ROLES.COPERNICUS_OPERATORS_CCM,
  ],
};

const COP_DEM_FULL_ACCESS_RIGHTS = {
  DOWNLOAD_PRODUCT_ROLES: [
    CCM_ROLES.COPERNICUS_SERVICES_CCM,
    CCM_ROLES.UNION_INST_CCM,
    CCM_ROLES.UNION_RESEARCH_PROJECTS_SPACE_CCM,
    CCM_ROLES.UNION_RESEARCH_PROJECTS_NON_SPACE_CCM,
    CCM_ROLES.PUBLIC_AUTH_CCM,
    CCM_ROLES.INT_ORG_NGO_CCM,
    CCM_ROLES.PUBLIC_CCM,
    CCM_ROLES.COPERNICUS_OPERATORS_CCM,
  ],
};

export const CCM_PRODUCT_TYPE_ACCESS_RIGHTS = {
  // DWH_MG2b_CORE_03
  HRG_THX__3_54FA: PARTIAL_2_ACCESS_RIGHTS,
  NAO_PMS__3_54FA: PARTIAL_2_ACCESS_RIGHTS,
  PHR_MS___3_54FA: PARTIAL_2_ACCESS_RIGHTS,

  // VHR_IMAGE_2015
  PHR_BUN_1A_71F4: VHR_COMMON_ACCESS_RIGHTS,
  PHR_BUN__3_71F4: VHR_COMMON_ACCESS_RIGHTS,
  NAO_BUN__3_71F4: VHR_COMMON_ACCESS_RIGHTS,
  WV1_PM4_OR_71F4: VHR_COMMON_ACCESS_RIGHTS,
  NAO_BUN_1A_71F4: VHR_COMMON_ACCESS_RIGHTS,
  GIS_PM4_SO_71F4: VHR_COMMON_ACCESS_RIGHTS,
  WV1_PM4_SO_71F4: VHR_COMMON_ACCESS_RIGHTS,
  WV3_PM4_OR_71F4: VHR_COMMON_ACCESS_RIGHTS,
  HRS_PM4_1C_71F4: VHR_COMMON_ACCESS_RIGHTS,
  GIS_PM4_OR_71F4: VHR_COMMON_ACCESS_RIGHTS,
  WV3_PM4_SO_71F4: VHR_COMMON_ACCESS_RIGHTS,
  SAR_SC_MGD_71F4: VHR_COMMON_ACCESS_RIGHTS,
  HRS_PM4_1B_71F4: VHR_COMMON_ACCESS_RIGHTS,

  // VHR_IMAGE_2018
  AIS_MSP_1G_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  AIS_MSP_1R_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  NAO_MS4__3_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  NAO_MS4_2A_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  DOV_MS_L1A_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  DOV_MS_L3A_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  PHR_MS__2A_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  OPT_MS4_1B_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  PHR_MS___3_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  OPT_MS4_1C_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  VHI_MS4_1C_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  VHI_MS4_1B_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  HRS_MS4_1C_E1F0: VHR_COMMON_ACCESS_RIGHTS,
  HRS_MS4_1B_E1F0: VHR_COMMON_ACCESS_RIGHTS,

  // VHR_IMAGE_2018_ENHANCED
  PHR_MS__2A_B34B: VHR_COMMON_ACCESS_RIGHTS,
  PHR_MS___3_B34B: VHR_COMMON_ACCESS_RIGHTS,
  AIS_MSP_1G_B34B: VHR_COMMON_ACCESS_RIGHTS,
  AIS_MSP_1R_B34B: VHR_COMMON_ACCESS_RIGHTS,
  OPT_MS4_1B_B34B: VHR_COMMON_ACCESS_RIGHTS,
  OPT_MS4_1C_B34B: VHR_COMMON_ACCESS_RIGHTS,
  NAO_MS4__3_B34B: VHR_COMMON_ACCESS_RIGHTS,
  NAO_MS4_2A_B34B: VHR_COMMON_ACCESS_RIGHTS,

  // VHR_IMAGE_2021
  WV3_MS4_SO_07B6: VHR_COMMON_ACCESS_RIGHTS,
  PHR_MS__2A_07B6: VHR_COMMON_ACCESS_RIGHTS,
  PHR_MS___3_07B6: VHR_COMMON_ACCESS_RIGHTS,
  NAO_MS4__3_07B6: VHR_COMMON_ACCESS_RIGHTS,
  NAO_MS4_2A_07B6: VHR_COMMON_ACCESS_RIGHTS,
  OPT_MS4_1B_07B6: VHR_COMMON_ACCESS_RIGHTS,
  OPT_MS4_1C_07B6: VHR_COMMON_ACCESS_RIGHTS,
  AIS_MSP_1G_07B6: VHR_COMMON_ACCESS_RIGHTS,
  AIS_MSP_1R_07B6: VHR_COMMON_ACCESS_RIGHTS,
  WV1_MS4_SO_07B6: VHR_COMMON_ACCESS_RIGHTS,
  GIS_MS4_SO_07B6: VHR_COMMON_ACCESS_RIGHTS,
  WV1_MS4_OR_07B6: VHR_COMMON_ACCESS_RIGHTS,
  WV3_MS4_OR_07B6: VHR_COMMON_ACCESS_RIGHTS,
  GIS_MS4_OR_07B6: VHR_COMMON_ACCESS_RIGHTS,
  S14_MS4_2A_07B6: VHR_COMMON_ACCESS_RIGHTS,
  S14_MS4__3_07B6: VHR_COMMON_ACCESS_RIGHTS,
  VHI_MS4_1B_07B6: VHR_COMMON_ACCESS_RIGHTS,
  VHI_MS4_1C_07B6: VHR_COMMON_ACCESS_RIGHTS,
  HRS_MS4_1B_07B6: VHR_COMMON_ACCESS_RIGHTS,
  HRS_MS4_1C_07B6: VHR_COMMON_ACCESS_RIGHTS,

  // DAP_MG2b_01
  HRG_THX__3_56FB: PARTIAL_2_ACCESS_RIGHTS,
  MSI_IMG_3A_56FB: PARTIAL_2_ACCESS_RIGHTS,
  HRG_T____3_56FB: PARTIAL_2_ACCESS_RIGHTS,
  HRG_J____3_56FB: PARTIAL_2_ACCESS_RIGHTS,
  PSM_OB1_3A_56FB: PARTIAL_2_ACCESS_RIGHTS,
  AV2_OBS_3A_56FB: PARTIAL_2_ACCESS_RIGHTS,
  BGI_PM4_SO_56FB: PARTIAL_2_ACCESS_RIGHTS,
  RSI_FUS__3_56FB: PARTIAL_2_ACCESS_RIGHTS,

  // VHR DEM 2018
  A3D_DEM_18_7854: VHR_COPERNICUS_SERVICES_ONLY_ACCESS_RIGHTS,

  // VHR1-2_Urban_Atlas_2012
  WV1_PM8_SO_5558: VHR_COMMON_ACCESS_RIGHTS,

  // COP DEM
  SAR_DGE_10_9319: COP_DEM_PARTIAL_ACCESS_RIGHTS,
  SAR_INS_10_52C5: COP_DEM_PARTIAL_ACCESS_RIGHTS,
  SAR_DGE_30_A4AD: COP_DEM_FULL_ACCESS_RIGHTS,
  SAR_DTE_30_615C: COP_DEM_FULL_ACCESS_RIGHTS,
  SAR_DGE_90_A407: COP_DEM_FULL_ACCESS_RIGHTS,
  SAR_DTE_90_61F6: COP_DEM_FULL_ACCESS_RIGHTS,

  // VHR_Urban_Atlas_2006-2009 (2) / DAP_MG2b_02
  AV2_OBS_3A_57BB: PARTIAL_2_ACCESS_RIGHTS,
  HRG_J____3_57BB: PARTIAL_2_ACCESS_RIGHTS,
  HRG_T____3_57BB: PARTIAL_2_ACCESS_RIGHTS,
  HRG_THX__3_57BB: PARTIAL_2_ACCESS_RIGHTS,
  PSM_OB1_3A_57BB: PARTIAL_2_ACCESS_RIGHTS,
};
