export const GENERAL_PNEO_PANCHROMATIC_COLLECTION = '00ffbd-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_MS4_COLLECTION = '0190d5-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_OR_MS_COLLECTION = '0272ac-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_OR_PAN_COLLECTION = '035162-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_OR_PAN_COLLECTION = '035e8b-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HS_SSC_VV_COLLECTION = '05111d-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HIM_AB_HH_COLLECTION = '068b29-YOUR-INSTANCEID-HERE';
export const FRTX_ICEYE_GRD_COG_VV_COLLECTION = '07960a-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_HIM_1B_HV_COLLECTION = '085131-YOUR-INSTANCEID-HERE';
export const GENERAL_RADARSAT_SLC_VV_COLLECTION = '0a6331-YOUR-INSTANCEID-HERE';
export const GENERAL_RADARSAT_SGF_HV_COLLECTION = '0ac5ef-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION = '0ce9fb-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_PANSHARPENED_4BANDS_COLLECTION = '0e0c1c-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SLH_SL_VV_COLLECTION = '0f310e-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_OR_PAN_COLLECTION = '15c458-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_NAO_MS_3_COLLECTION = '1bc361-YOUR-INSTANCEID-HERE';
export const GENERAL_SKYSAT_MS_4_COLLECTION = '1c8f8d-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HIM_AU_HH_COLLECTION = '1fb07d-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SKY_CPS_3P_COLLECTION = '1ffe14-YOUR-INSTANCEID-HERE';
export const CSESA_GHGSAT_CH4_COLLECTION = '247ad6-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_3_PAN_COLLECTION = '2596b8-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_UF_SGF_HH_COLLECTION = '2653ee-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_SO_MS_COLLECTION = '285fe9-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_SO_MS_COLLECTION = '2954da-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_SO_MS_COLLECTION = '2a0b9b-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_4PS_COLLECTION = '2b2c9f-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_OR_MS_COLLECTION = '2c34ec-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV6_PAN_OR_COLLECTION = '2d69f9-YOUR-INSTANCEID-HERE';
export const FRTX_GHGSAT_CH4_COLLECTION = '2e3f54-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_8MS_COLLECTION = '2f6448-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_SSC_HH_COLLECTION = '30ba3f-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_MS_3_COLLECTION = '30dab5-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_SC1_AB_HH_COLLECTION = '31194d-YOUR-INSTANCEID-HERE';
export const FRTX_PNEO_PANSHARPENED_4BANDS_COLLECTION = '318af2-YOUR-INSTANCEID-HERE';
export const GENERAL_GHGSAT_CH4_COLLECTION = '31b3af-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_UW_SLC_HH_COLLECTION = '355d1e-YOUR-INSTANCEID-HERE';
export const GENERAL_SKYSAT_PAN_COLLECTION = '35d8b7-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_BUN_1A_PAN_COLLECTION = '375e13-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_SO_PAN_COLLECTION = '37d9ea-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_MGD_HH_COLLECTION = '38d100-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_FUS_3_COLLECTION = '399f5b-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_OR_PAN_COLLECTION = '3f04b6-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_SO_PAN_COLLECTION = '4216fb-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_MULTISPECTRAL_6BANDS_COLLECTION = '43445b-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PSH_OR_COLLECTION = '48648b-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_OR_MS_COLLECTION = '4a2cdc-YOUR-INSTANCEID-HERE';
export const GENERAL_RADARSAT_SGF_HH_COLLECTION = '4da689-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_XF_SGF_HH_COLLECTION = '4e1a4b-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_CSG_HIM_AB_HH_COLLECTION = '4fe8e9-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_GEC_SE_HH_COLLECTION = '506399-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HIM_1B_HH_COLLECTION = '572622-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_4MS_COLLECTION = '58b3b6-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_1A_MS_COLLECTION = '5a03ce-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION = '5d5556-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SCW_1B_HH_COLLECTION = '60c1d9-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_PANSHARPENED_COLLECTION = '60cfe0-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_RGB_COLLECTION = '61439d-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PSH_OR_COLLECTION = '6177a3-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_PANSHARPENED_6BANDS_COLLECTION = '638d5a-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION = '63d6aa-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_PAN_COLLECTION = '6470de-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_S2C_AB_HH_COLLECTION = '662e80-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_8MS_COLLECTION = '689848-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_ST_SSC_HH_COLLECTION = '6af818-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_SM_SSC_HH_COLLECTION = '6b7a5d-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION = '6b8959-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_ST_SSC_HH_COLLECTION = '6bcb32-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_MS4_OR_COLLECTION = '6eb9dd-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_BUN_1A_MS_COLLECTION = '6fd414-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_RGB_COLLECTION = '7018b0-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_PSH_OR_COLLECTION = '71fa06-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV6_PAN_SO_COLLECTION = '735a05-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_SO_PAN_COLLECTION = '74595b-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_HS_SSC_VV_COLLECTION = '761f22-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_4PS_COLLECTION = '763b3c-YOUR-INSTANCEID-HERE';
export const GENERAL_PLANETSCOPE_MS_4_COLLECTION = '7a2b6e-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_MS4_OR_COLLECTION = '7b7f4d-YOUR-INSTANCEID-HERE';
export const FRTX_LEGION_PAN_COLLECTION = '7ed154-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_8MS_COLLECTION = '7f4fca-YOUR-INSTANCEID-HERE';
export const GENERAL_PHR_PANSHARPENED_4BANDS_COLLECTION = '7fa2f8-YOUR-INSTANCEID-HERE';
export const CSESA_RADARSAT_SGF_HV_COLLECTION = '81f5ea-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_PAN_COLLECTION = '821a17-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_SO_MS_COLLECTION = '85956f-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_DOV_MS_L3A_COLLECTION = '86ee03-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_OR_PAN_COLLECTION = '885c71-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PNE_PMS_3_COLLECTION = '8a8565-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_PM4_SO_MS_COLLECTION = '8a93e9-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_FUS_3_COLLECTION = '8c558d-YOUR-INSTANCEID-HERE';
export const CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION = '911da2-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_OR_MS_COLLECTION = '947ad5-YOUR-INSTANCEID-HERE';
export const GENERAL_ICEYE_SLC_COG_VV_COLLECTION = '97ad88-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SKY_CPS_3P_COLLECTION = '9b2d5b-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_3_MS_COLLECTION = '9b2d96-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PSH_OR_COLLECTION = '9c4bb1-YOUR-INSTANCEID-HERE';
export const GENERAL_ICEYE_GRD_COG_VV_COLLECTION = '9d4102-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HS_SSC_HH_VV_COLLECTION = '9dc5eb-YOUR-INSTANCEID-HERE';
export const CSESA_RADARSAT_SGF_HH_COLLECTION = '9e5da9-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_1A_PAN_COLLECTION = 'a04ed7-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_MS4_OR_COLLECTION = 'a0f339-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_PAN_COLLECTION = 'a10892-YOUR-INSTANCEID-HERE';
export const GENERAL_RADARSAT_SLC_HH_COLLECTION = 'a10a9b-YOUR-INSTANCEID-HERE';
export const GENERAL_SKYSAT_PANS_COLLECTION = 'a18cf4-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_PM4_SO_PAN_COLLECTION = 'a331c2-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_WX_SGF_HH_COLLECTION = 'a343c8-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_SO_PAN_COLLECTION = 'a6adb4-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_SSC_HH_HV_COLLECTION = 'abe49d-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_XF_SLC_HH_COLLECTION = 'acddec-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SC_MGD_VV_COLLECTION = 'ad9443-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_SLH_SL_VV_COLLECTION = 'aecd0f-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_PSH_COLLECTION = 'b223ca-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_DOV_MS_L3A_COLLECTION = 'b27ba1-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_4PS_COLLECTION = 'b2d156-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_SP2_AB_VV_COLLECTION = 'b2e800-YOUR-INSTANCEID-HERE';
export const GENERAL_ICEYE_TEST_VV_COLLECTION = 'ba2e49-YOUR-INSTANCEID-HERE';
export const CSESA_SKYSAT_MS_4_COLLECTION = 'bf3374-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_HIM_1B_HH_COLLECTION = 'c7ba36-YOUR-INSTANCEID-HERE';
export const CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION = 'c8c943-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PSH_SO_COLLECTION = 'ca5264-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SC_MGD_HH_COLLECTION = 'ca764d-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_NAO_PMS_3_COLLECTION = 'cc7767-YOUR-INSTANCEID-HERE';
export const GENERAL_RADARSAT_SLC_VH_COLLECTION = 'cc81cb-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_GR_VV_COLLECTION = 'cceca7-YOUR-INSTANCEID-HERE';
export const CSESA_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION = 'd0ff88-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_UW_SGF_HH_COLLECTION = 'd1119b-YOUR-INSTANCEID-HERE';
export const GENERAL_PLANETSCOPE_MS_8_COLLECTION = 'd15b75-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PSH_OR_COLLECTION = 'd291e9-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_PS3_COLLECTION = 'd3fd62-YOUR-INSTANCEID-HERE';
export const GENERAL_PAZ_GEC_RE_HH_COLLECTION = 'd7bdf6-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_SC1_1B_HH_COLLECTION = 'da80bd-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_OR_MS_COLLECTION = 'dfb0ff-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SP2_AB_VV_COLLECTION = 'e63bea-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_HRS_PSH_1C_COLLECTION = 'e8c99f-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SCW_1B_VV_COLLECTION = 'e9a7b4-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_SO_MS_COLLECTION = 'eb0ff4-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_MGD_HV_COLLECTION = 'f11058-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_HIM_AB_HH_COLLECTION = 'f3667e-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_SO_PAN_COLLECTION = 'f57920-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_PAN_COLLECTION = 'f589b6-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_4MS_COLLECTION = 'f59c5e-YOUR-INSTANCEID-HERE';
export const GENERAL_PHR_PANCHROMATIC_COLLECTION = 'f78e71-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SCW_AB_HH_COLLECTION = 'f7e96e-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_4MS_COLLECTION = 'f86565-YOUR-INSTANCEID-HERE';
export const GENERAL_PHR_MULTISPECTRAL_4BANDS_COLLECTION = 'f87d51-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_CSG_S2C_AB_HH_COLLECTION = 'fe1855-YOUR-INSTANCEID-HERE';

export const RRD_COLLECTIONS = [
  GENERAL_PNEO_PANCHROMATIC_COLLECTION,
  GENERAL_GEOSAT_MS4_COLLECTION,
  PRISM_FRTX_GIS_PM4_OR_MS_COLLECTION,
  PRISM_FRTX_WV1_PM4_OR_PAN_COLLECTION,
  PRISM_FRTX_GIS_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_SAR_HS_SSC_VV_COLLECTION,
  PRISM_GENERAL_SAR_HIM_AB_HH_COLLECTION,
  FRTX_ICEYE_GRD_COG_VV_COLLECTION,
  PRISM_GENERAL_CSG_HIM_1B_HV_COLLECTION,
  GENERAL_RADARSAT_SLC_VV_COLLECTION,
  GENERAL_RADARSAT_SGF_HV_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION,
  GENERAL_PNEO_PANSHARPENED_4BANDS_COLLECTION,
  PRISM_GENERAL_SAR_SLH_SL_VV_COLLECTION,
  PRISM_FRTX_WV3_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_NAO_MS_3_COLLECTION,
  GENERAL_SKYSAT_MS_4_COLLECTION,
  PRISM_GENERAL_SAR_HIM_AU_HH_COLLECTION,
  PRISM_FRTX_SKY_CPS_3P_COLLECTION,
  CSESA_GHGSAT_CH4_COLLECTION,
  PRISM_FRTX_PHR_BUN_3_PAN_COLLECTION,
  PRISM_GENERAL_SAR_UF_SGF_HH_COLLECTION,
  PRISM_GENERAL_WV1_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_GIS_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_WV1_PM4_SO_MS_COLLECTION,
  GENERAL_WORLDVIEW_4PS_COLLECTION,
  PRISM_GENERAL_WV1_PM4_OR_MS_COLLECTION,
  PRISM_FRTX_WV6_PAN_OR_COLLECTION,
  FRTX_GHGSAT_CH4_COLLECTION,
  CSESA_WORLDVIEW_8MS_COLLECTION,
  PRISM_GENERAL_SAR_SM_SSC_HH_COLLECTION,
  PRISM_GENERAL_PHR_MS_3_COLLECTION,
  PRISM_GENERAL_CSG_SC1_AB_HH_COLLECTION,
  FRTX_PNEO_PANSHARPENED_4BANDS_COLLECTION,
  GENERAL_GHGSAT_CH4_COLLECTION,
  PRISM_GENERAL_SAR_UW_SLC_HH_COLLECTION,
  GENERAL_SKYSAT_PAN_COLLECTION,
  PRISM_GENERAL_PHR_BUN_1A_PAN_COLLECTION,
  PRISM_FRTX_GIS_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_SM_MGD_HH_COLLECTION,
  PRISM_FRTX_PHR_FUS_3_COLLECTION,
  PRISM_GENERAL_WV3_PM4_OR_PAN_COLLECTION,
  PRISM_FRTX_WV3_PM4_SO_PAN_COLLECTION,
  GENERAL_PNEO_MULTISPECTRAL_6BANDS_COLLECTION,
  PRISM_GENERAL_WV1_PSH_OR_COLLECTION,
  PRISM_FRTX_WV3_PM4_OR_MS_COLLECTION,
  GENERAL_RADARSAT_SGF_HH_COLLECTION,
  PRISM_GENERAL_SAR_XF_SGF_HH_COLLECTION,
  PRISM_FRTX_CSG_HIM_AB_HH_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_GEC_SE_HH_COLLECTION,
  PRISM_GENERAL_SAR_HIM_1B_HH_COLLECTION,
  GENERAL_WORLDVIEW_4MS_COLLECTION,
  PRISM_FRTX_PHR_BUN_1A_MS_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION,
  PRISM_GENERAL_SAR_SCW_1B_HH_COLLECTION,
  GENERAL_PNEO_PANSHARPENED_COLLECTION,
  CSESA_WORLDVIEW_RGB_COLLECTION,
  PRISM_FRTX_WV3_PSH_OR_COLLECTION,
  GENERAL_PNEO_PANSHARPENED_6BANDS_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION,
  CSESA_WORLDVIEW_PAN_COLLECTION,
  PRISM_GENERAL_CSG_S2C_AB_HH_COLLECTION,
  GENERAL_LEGION_8MS_COLLECTION,
  PRISM_FRTX_SAR_ST_SSC_HH_COLLECTION,
  PRISM_FRTX_SAR_SM_SSC_HH_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION,
  PRISM_GENERAL_SAR_ST_SSC_HH_COLLECTION,
  PRISM_GENERAL_WV1_MS4_OR_COLLECTION,
  PRISM_GENERAL_PHR_BUN_1A_MS_COLLECTION,
  GENERAL_WORLDVIEW_RGB_COLLECTION,
  PRISM_GENERAL_GIS_PSH_OR_COLLECTION,
  PRISM_FRTX_WV6_PAN_SO_COLLECTION,
  PRISM_GENERAL_WV1_PM4_SO_PAN_COLLECTION,
  PRISM_FRTX_SAR_HS_SSC_VV_COLLECTION,
  GENERAL_LEGION_4PS_COLLECTION,
  GENERAL_PLANETSCOPE_MS_4_COLLECTION,
  PRISM_GENERAL_WV3_MS4_OR_COLLECTION,
  FRTX_LEGION_PAN_COLLECTION,
  GENERAL_WORLDVIEW_8MS_COLLECTION,
  GENERAL_PHR_PANSHARPENED_4BANDS_COLLECTION,
  CSESA_RADARSAT_SGF_HV_COLLECTION,
  GENERAL_GEOSAT_PAN_COLLECTION,
  PRISM_GENERAL_WV3_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_DOV_MS_L3A_COLLECTION,
  PRISM_GENERAL_WV1_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_PNE_PMS_3_COLLECTION,
  PRISM_GENERAL_GIS_PM4_SO_MS_COLLECTION,
  PRISM_GENERAL_PHR_FUS_3_COLLECTION,
  CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION,
  PRISM_FRTX_WV1_PM4_OR_MS_COLLECTION,
  GENERAL_ICEYE_SLC_COG_VV_COLLECTION,
  PRISM_GENERAL_SKY_CPS_3P_COLLECTION,
  PRISM_FRTX_PHR_BUN_3_MS_COLLECTION,
  PRISM_FRTX_GIS_PSH_OR_COLLECTION,
  GENERAL_ICEYE_GRD_COG_VV_COLLECTION,
  PRISM_GENERAL_SAR_HS_SSC_HH_VV_COLLECTION,
  CSESA_RADARSAT_SGF_HH_COLLECTION,
  PRISM_FRTX_PHR_BUN_1A_PAN_COLLECTION,
  PRISM_GENERAL_GIS_MS4_OR_COLLECTION,
  GENERAL_WORLDVIEW_PAN_COLLECTION,
  GENERAL_RADARSAT_SLC_HH_COLLECTION,
  GENERAL_SKYSAT_PANS_COLLECTION,
  PRISM_GENERAL_GIS_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_WX_SGF_HH_COLLECTION,
  PRISM_GENERAL_WV3_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_SM_SSC_HH_HV_COLLECTION,
  PRISM_GENERAL_SAR_XF_SLC_HH_COLLECTION,
  PRISM_GENERAL_SAR_SC_MGD_VV_COLLECTION,
  PRISM_FRTX_SAR_SLH_SL_VV_COLLECTION,
  GENERAL_GEOSAT_PSH_COLLECTION,
  PRISM_GENERAL_DOV_MS_L3A_COLLECTION,
  CSESA_WORLDVIEW_4PS_COLLECTION,
  PRISM_FRTX_SAR_SP2_AB_VV_COLLECTION,
  GENERAL_ICEYE_TEST_VV_COLLECTION,
  CSESA_SKYSAT_MS_4_COLLECTION,
  PRISM_GENERAL_CSG_HIM_1B_HH_COLLECTION,
  CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION,
  PRISM_FRTX_WV3_PSH_SO_COLLECTION,
  PRISM_GENERAL_SAR_SC_MGD_HH_COLLECTION,
  PRISM_GENERAL_NAO_PMS_3_COLLECTION,
  GENERAL_RADARSAT_SLC_VH_COLLECTION,
  PRISM_GENERAL_SAR_SM_GR_VV_COLLECTION,
  CSESA_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION,
  PRISM_GENERAL_SAR_UW_SGF_HH_COLLECTION,
  GENERAL_PLANETSCOPE_MS_8_COLLECTION,
  PRISM_GENERAL_WV3_PSH_OR_COLLECTION,
  GENERAL_GEOSAT_PS3_COLLECTION,
  GENERAL_PAZ_GEC_RE_HH_COLLECTION,
  PRISM_GENERAL_CSG_SC1_1B_HH_COLLECTION,
  PRISM_GENERAL_WV3_PM4_OR_MS_COLLECTION,
  PRISM_GENERAL_SAR_SP2_AB_VV_COLLECTION,
  PRISM_GENERAL_HRS_PSH_1C_COLLECTION,
  PRISM_GENERAL_SAR_SCW_1B_VV_COLLECTION,
  PRISM_FRTX_WV3_PM4_SO_MS_COLLECTION,
  PRISM_GENERAL_SAR_SM_MGD_HV_COLLECTION,
  PRISM_GENERAL_CSG_HIM_AB_HH_COLLECTION,
  PRISM_FRTX_WV1_PM4_SO_PAN_COLLECTION,
  GENERAL_LEGION_PAN_COLLECTION,
  CSESA_WORLDVIEW_4MS_COLLECTION,
  GENERAL_PHR_PANCHROMATIC_COLLECTION,
  PRISM_GENERAL_SAR_SCW_AB_HH_COLLECTION,
  GENERAL_LEGION_4MS_COLLECTION,
  GENERAL_PHR_MULTISPECTRAL_4BANDS_COLLECTION,
  PRISM_FRTX_CSG_S2C_AB_HH_COLLECTION,
];
