export const PRISM_GENERAL_SAR_SP2_AB_VV_COLLECTION = '009acb-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_SC1_1B_HH_COLLECTION = '020979-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_WX_SGF_HH_COLLECTION = '0435a5-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_UW_SGF_HH_COLLECTION = '05cee9-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_4MS_COLLECTION = '07ff69-YOUR-INSTANCEID-HERE';
export const GENERAL_SPOT_PANSHARPENED_4BANDS_COLLECTION = '080129-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PSH_OR_COLLECTION = '0843ef-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_FUS_3_COLLECTION = '0a172d-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION = '0ac427-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PSH_SO_COLLECTION = '0b6911-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_PANCHROMATIC_COLLECTION = '0d1467-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_SO_PAN_COLLECTION = '0f4740-YOUR-INSTANCEID-HERE';
export const CSESA_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION = '0ff4a8-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_HIM_AB_HH_COLLECTION = '1008a7-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_SO_MS_COLLECTION = '111660-YOUR-INSTANCEID-HERE';
export const GENERAL_PLANETSCOPE_MS_8_COLLECTION = '1530d6-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_PSH_COLLECTION = '15adf2-YOUR-INSTANCEID-HERE';
export const GENERAL_ICEYE_GRD_COG_VV_COLLECTION = '160f0b-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_DOV_MS_L3A_COLLECTION = '164c1a-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_RGB_COLLECTION = '165cfe-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SC_MGD_HH_COLLECTION = '18337b-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_PSH_OR_COLLECTION = '18ccaa-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HS_SSC_VV_COLLECTION = '208d51-YOUR-INSTANCEID-HERE';
export const GENERAL_PAZ_GEC_RE_HH_COLLECTION = '20a862-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_ST_SSC_HH_COLLECTION = '214f04-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_4MS_COLLECTION = '23a515-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_OR_PAN_COLLECTION = '255322-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_OR_PAN_COLLECTION = '264e33-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HS_SSC_HH_VV_COLLECTION = '28c516-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_MS4_OR_COLLECTION = '2b5548-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_NAO_MS_3_COLLECTION = '2d6fa7-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_SP2_AB_VV_COLLECTION = '2dac6b-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_4PS_COLLECTION = '2f0a9f-YOUR-INSTANCEID-HERE';
export const CSESA_SKYSAT_PANS_COLLECTION = '2fd85a-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_SO_MS_COLLECTION = '316b3b-YOUR-INSTANCEID-HERE';
export const FRTX_LEGION_4PS_COLLECTION = '3532fb-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_PM4_SO_MS_COLLECTION = '35def3-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_SO_PAN_COLLECTION = '365a25-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_SO_MS_COLLECTION = '36c045-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV6_PAN_OR_COLLECTION = '38c2b5-YOUR-INSTANCEID-HERE';
export const GENERAL_PLANETSCOPE_MS_4_COLLECTION = '3bed57-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_MULTISPECTRAL_4BANDS_COLLECTION = '3ea488-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_OR_MS_COLLECTION = '40632e-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_1A_MS_COLLECTION = '4201f0-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_HRS_PSH_1C_COLLECTION = '461402-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SCW_1B_VV_COLLECTION = '470284-YOUR-INSTANCEID-HERE';
export const GENERAL_SKYSAT_MS_4_COLLECTION = '47e27f-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_HS_SSC_VV_COLLECTION = '4a4397-YOUR-INSTANCEID-HERE';
export const FRTX_LEGION_RGB_COLLECTION = '4bcb6c-YOUR-INSTANCEID-HERE';
export const FRTX_PLANETSCOPE_MS_4_COLLECTION = '4dcc9a-YOUR-INSTANCEID-HERE';
export const FRTX_SKYSAT_PANS_COLLECTION = '4ff19b-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_OR_MS_COLLECTION = '568b3d-YOUR-INSTANCEID-HERE';
export const GENERAL_RADARSAT_SGF_HH_COLLECTION = '56a788-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_RGB_COLLECTION = '56baa2-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_OR_MS_COLLECTION = '5b5245-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_OR_MS_COLLECTION = '5cbc30-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HIM_AU_HH_COLLECTION = '5d4427-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SC_MGD_VV_COLLECTION = '5de3b2-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_8MS_COLLECTION = '5ec531-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SCW_1B_HH_COLLECTION = '6077cd-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_1A_PAN_COLLECTION = '6170e4-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_ST_SSC_HH_COLLECTION = '61bd53-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_PAN_COLLECTION = '62614c-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PSH_OR_COLLECTION = '642c55-YOUR-INSTANCEID-HERE';
export const GENERAL_SKYSAT_PANS_COLLECTION = '647498-YOUR-INSTANCEID-HERE';
export const GENERAL_RADARSAT_SGF_HV_COLLECTION = '6549cb-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_PAN_COLLECTION = '6b2f23-YOUR-INSTANCEID-HERE';
export const FRTX_LEGION_4MS_COLLECTION = '6c9043-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HIM_AB_HH_COLLECTION = '71e890-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_GR_VV_COLLECTION = '73a3fd-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_SLH_SL_VV_COLLECTION = '74d04d-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_MS_3_COLLECTION = '74def4-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_SO_PAN_COLLECTION = '7c43a4-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PM4_SO_MS_COLLECTION = '7c807c-YOUR-INSTANCEID-HERE';
export const GENERAL_ICEYE_SLC_COG_VV_COLLECTION = '7e47f8-YOUR-INSTANCEID-HERE';
export const GENERAL_GHGSAT_CH4_COLLECTION = '7eb4e1-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_HIM_1B_HH_COLLECTION = '81fbf1-YOUR-INSTANCEID-HERE';
export const CSESA_LEGION_4MS_COLLECTION = '83472d-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_GIS_PM4_SO_PAN_COLLECTION = '8524ed-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_HIM_1B_HH_COLLECTION = '85d3fe-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_MULTISPECTRAL_6BANDS_COLLECTION = '85e5bd-YOUR-INSTANCEID-HERE';
export const FRTX_WORLDVIEW_PAN_COLLECTION = '901aa8-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PNE_PMS_3_COLLECTION = '908229-YOUR-INSTANCEID-HERE';
export const FRTX_ICEYE_GRD_COG_VV_COLLECTION = '921c1f-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_UW_SLC_HH_COLLECTION = '99d691-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_SC1_AB_HH_COLLECTION = '9cd1f5-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_SO_MS_COLLECTION = '9e03fe-YOUR-INSTANCEID-HERE';
export const GENERAL_PHR_PANSHARPENED_4BANDS_COLLECTION = '9f851c-YOUR-INSTANCEID-HERE';
export const CSESA_WORLDVIEW_4PS_COLLECTION = 'a0aa9c-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION = 'a188b9-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_XF_SGF_HH_COLLECTION = 'a30238-YOUR-INSTANCEID-HERE';
export const CSESA_LEGION_PAN_COLLECTION = 'a56292-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_OR_PAN_COLLECTION = 'a7acfd-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_DOV_MS_L3A_COLLECTION = 'aa0d51-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_PM4_SO_PAN_COLLECTION = 'ab0615-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_8MS_COLLECTION = 'add999-YOUR-INSTANCEID-HERE';
export const CSESA_LEGION_4PS_COLLECTION = 'ae0fcf-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SKY_CPS_3P_COLLECTION = 'af2335-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_SSC_HH_HV_COLLECTION = 'b3fd06-YOUR-INSTANCEID-HERE';
export const FRTX_WORLDVIEW_RGB_COLLECTION = 'b57dba-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_GIS_PSH_OR_COLLECTION = 'b68f5a-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_OR_PAN_COLLECTION = 'b7f122-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_PAN_COLLECTION = 'b8c535-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_S2C_AB_HH_COLLECTION = 'ba7458-YOUR-INSTANCEID-HERE';
export const FRTX_WORLDVIEW_4PS_COLLECTION = 'bfc013-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SAR_SM_SSC_HH_COLLECTION = 'bff365-YOUR-INSTANCEID-HERE';
export const GENERAL_SPOT_MULTISPECTRAL_4BANDS_COLLECTION = 'c16fc4-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION = 'c18db7-YOUR-INSTANCEID-HERE';
export const GENERAL_SPOT_PANCHROMATIC_COLLECTION = 'c222b6-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_MS4_OR_COLLECTION = 'c24722-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PM4_OR_MS_COLLECTION = 'c2a734-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_CSG_HIM_AB_HH_COLLECTION = 'c2b4de-YOUR-INSTANCEID-HERE';
export const FRTX_WORLDVIEW_4MS_COLLECTION = 'c55ef0-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_PAN_COLLECTION = 'c5a49e-YOUR-INSTANCEID-HERE';
export const CSESA_GEOSAT_PSH_COLLECTION = 'c82f5a-YOUR-INSTANCEID-HERE';
export const FRTX_ICEYE_SLC_COG_VV_COLLECTION = 'c8eef1-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SCW_AB_HH_COLLECTION = 'c8f4cd-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_SSC_HH_COLLECTION = 'c98649-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_BUN_1A_MS_COLLECTION = 'd047ad-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_CSG_S2C_AB_HH_COLLECTION = 'd17df2-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_NAO_PMS_3_COLLECTION = 'd19eef-YOUR-INSTANCEID-HERE';
export const GENERAL_WORLDVIEW_4PS_COLLECTION = 'd1e30e-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_PHR_BUN_1A_PAN_COLLECTION = 'd2e9f2-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_3_PAN_COLLECTION = 'd4c438-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_MGD_HH_COLLECTION = 'd5a261-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_SKY_CPS_3P_COLLECTION = 'd6b808-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV3_PM4_OR_PAN_COLLECTION = 'd7b90b-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_WV1_MS4_OR_COLLECTION = 'd9d7d2-YOUR-INSTANCEID-HERE';
export const GENERAL_PNEO_PANSHARPENED_4BANDS_COLLECTION = 'd9dc35-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV1_PM4_SO_PAN_COLLECTION = 'ddf37c-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_UF_SGF_HH_COLLECTION = 'de46a8-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SLH_SL_VV_COLLECTION = 'dfef8f-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV3_PSH_OR_COLLECTION = 'e0e9ce-YOUR-INSTANCEID-HERE';
export const GENERAL_SKYSAT_PAN_COLLECTION = 'e17823-YOUR-INSTANCEID-HERE';
export const FRTX_LEGION_PAN_COLLECTION = 'e45846-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_FUS_3_COLLECTION = 'e60928-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_PHR_BUN_3_MS_COLLECTION = 'e89c56-YOUR-INSTANCEID-HERE';
export const PRISM_FRTX_WV6_PAN_SO_COLLECTION = 'e8e3c3-YOUR-INSTANCEID-HERE';
export const GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION = 'e9f00a-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_SM_MGD_HV_COLLECTION = 'ebb5f9-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_CSG_HIM_1B_HV_COLLECTION = 'ec5ec6-YOUR-INSTANCEID-HERE';
export const CSESA_PLANETSCOPE_MS_4_COLLECTION = 'f3a2a1-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_PS3_COLLECTION = 'f3eff4-YOUR-INSTANCEID-HERE';
export const GENERAL_LEGION_4MS_COLLECTION = 'f86364-YOUR-INSTANCEID-HERE';
export const PRISM_GENERAL_SAR_XF_SLC_HH_COLLECTION = 'fba2a2-YOUR-INSTANCEID-HERE';
export const GENERAL_GEOSAT_MS4_COLLECTION = 'fd97c0-YOUR-INSTANCEID-HERE';

export const RRD_COLLECTIONS = [
  PRISM_GENERAL_SAR_SP2_AB_VV_COLLECTION,
  PRISM_GENERAL_CSG_SC1_1B_HH_COLLECTION,
  PRISM_GENERAL_SAR_WX_SGF_HH_COLLECTION,
  PRISM_GENERAL_SAR_UW_SGF_HH_COLLECTION,
  GENERAL_WORLDVIEW_4MS_COLLECTION,
  GENERAL_SPOT_PANSHARPENED_4BANDS_COLLECTION,
  PRISM_GENERAL_WV3_PSH_OR_COLLECTION,
  PRISM_GENERAL_PHR_FUS_3_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION,
  PRISM_FRTX_WV3_PSH_SO_COLLECTION,
  GENERAL_PNEO_PANCHROMATIC_COLLECTION,
  PRISM_GENERAL_WV3_PM4_SO_PAN_COLLECTION,
  CSESA_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION,
  PRISM_GENERAL_CSG_HIM_AB_HH_COLLECTION,
  PRISM_FRTX_WV3_PM4_SO_MS_COLLECTION,
  GENERAL_PLANETSCOPE_MS_8_COLLECTION,
  GENERAL_GEOSAT_PSH_COLLECTION,
  GENERAL_ICEYE_GRD_COG_VV_COLLECTION,
  PRISM_GENERAL_DOV_MS_L3A_COLLECTION,
  GENERAL_LEGION_RGB_COLLECTION,
  PRISM_GENERAL_SAR_SC_MGD_HH_COLLECTION,
  PRISM_GENERAL_GIS_PSH_OR_COLLECTION,
  PRISM_GENERAL_SAR_HS_SSC_VV_COLLECTION,
  GENERAL_PAZ_GEC_RE_HH_COLLECTION,
  PRISM_FRTX_SAR_ST_SSC_HH_COLLECTION,
  CSESA_WORLDVIEW_4MS_COLLECTION,
  PRISM_FRTX_GIS_PM4_OR_PAN_COLLECTION,
  PRISM_FRTX_WV3_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_SAR_HS_SSC_HH_VV_COLLECTION,
  PRISM_GENERAL_GIS_MS4_OR_COLLECTION,
  PRISM_GENERAL_NAO_MS_3_COLLECTION,
  PRISM_FRTX_SAR_SP2_AB_VV_COLLECTION,
  GENERAL_LEGION_4PS_COLLECTION,
  CSESA_SKYSAT_PANS_COLLECTION,
  PRISM_GENERAL_WV3_PM4_SO_MS_COLLECTION,
  FRTX_LEGION_4PS_COLLECTION,
  PRISM_GENERAL_GIS_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_GIS_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_WV1_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_WV6_PAN_OR_COLLECTION,
  GENERAL_PLANETSCOPE_MS_4_COLLECTION,
  GENERAL_PNEO_MULTISPECTRAL_4BANDS_COLLECTION,
  PRISM_GENERAL_WV1_PM4_OR_MS_COLLECTION,
  PRISM_FRTX_PHR_BUN_1A_MS_COLLECTION,
  PRISM_GENERAL_HRS_PSH_1C_COLLECTION,
  PRISM_GENERAL_SAR_SCW_1B_VV_COLLECTION,
  GENERAL_SKYSAT_MS_4_COLLECTION,
  PRISM_FRTX_SAR_HS_SSC_VV_COLLECTION,
  FRTX_LEGION_RGB_COLLECTION,
  FRTX_PLANETSCOPE_MS_4_COLLECTION,
  FRTX_SKYSAT_PANS_COLLECTION,
  PRISM_FRTX_GIS_PM4_OR_MS_COLLECTION,
  GENERAL_RADARSAT_SGF_HH_COLLECTION,
  GENERAL_WORLDVIEW_RGB_COLLECTION,
  PRISM_GENERAL_WV3_PM4_OR_MS_COLLECTION,
  PRISM_FRTX_WV1_PM4_OR_MS_COLLECTION,
  PRISM_GENERAL_SAR_HIM_AU_HH_COLLECTION,
  PRISM_GENERAL_SAR_SC_MGD_VV_COLLECTION,
  GENERAL_WORLDVIEW_8MS_COLLECTION,
  PRISM_GENERAL_SAR_SCW_1B_HH_COLLECTION,
  PRISM_FRTX_PHR_BUN_1A_PAN_COLLECTION,
  PRISM_GENERAL_SAR_ST_SSC_HH_COLLECTION,
  GENERAL_GEOSAT_PAN_COLLECTION,
  PRISM_GENERAL_WV1_PSH_OR_COLLECTION,
  GENERAL_SKYSAT_PANS_COLLECTION,
  GENERAL_RADARSAT_SGF_HV_COLLECTION,
  CSESA_WORLDVIEW_PAN_COLLECTION,
  FRTX_LEGION_4MS_COLLECTION,
  PRISM_GENERAL_SAR_HIM_AB_HH_COLLECTION,
  PRISM_GENERAL_SAR_SM_GR_VV_COLLECTION,
  PRISM_FRTX_SAR_SLH_SL_VV_COLLECTION,
  PRISM_GENERAL_PHR_MS_3_COLLECTION,
  PRISM_FRTX_WV3_PM4_SO_PAN_COLLECTION,
  PRISM_FRTX_GIS_PM4_SO_MS_COLLECTION,
  GENERAL_ICEYE_SLC_COG_VV_COLLECTION,
  GENERAL_GHGSAT_CH4_COLLECTION,
  PRISM_GENERAL_CSG_HIM_1B_HH_COLLECTION,
  CSESA_LEGION_4MS_COLLECTION,
  PRISM_GENERAL_GIS_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_HIM_1B_HH_COLLECTION,
  GENERAL_PNEO_MULTISPECTRAL_6BANDS_COLLECTION,
  FRTX_WORLDVIEW_PAN_COLLECTION,
  PRISM_GENERAL_PNE_PMS_3_COLLECTION,
  FRTX_ICEYE_GRD_COG_VV_COLLECTION,
  PRISM_GENERAL_SAR_UW_SLC_HH_COLLECTION,
  PRISM_GENERAL_CSG_SC1_AB_HH_COLLECTION,
  PRISM_FRTX_WV1_PM4_SO_MS_COLLECTION,
  GENERAL_PHR_PANSHARPENED_4BANDS_COLLECTION,
  CSESA_WORLDVIEW_4PS_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION,
  PRISM_GENERAL_SAR_XF_SGF_HH_COLLECTION,
  CSESA_LEGION_PAN_COLLECTION,
  PRISM_GENERAL_WV1_PM4_OR_PAN_COLLECTION,
  PRISM_FRTX_DOV_MS_L3A_COLLECTION,
  PRISM_GENERAL_WV1_PM4_SO_PAN_COLLECTION,
  GENERAL_LEGION_8MS_COLLECTION,
  CSESA_LEGION_4PS_COLLECTION,
  PRISM_GENERAL_SKY_CPS_3P_COLLECTION,
  PRISM_GENERAL_SAR_SM_SSC_HH_HV_COLLECTION,
  FRTX_WORLDVIEW_RGB_COLLECTION,
  PRISM_FRTX_GIS_PSH_OR_COLLECTION,
  PRISM_FRTX_WV1_PM4_OR_PAN_COLLECTION,
  GENERAL_WORLDVIEW_PAN_COLLECTION,
  PRISM_GENERAL_CSG_S2C_AB_HH_COLLECTION,
  FRTX_WORLDVIEW_4PS_COLLECTION,
  PRISM_FRTX_SAR_SM_SSC_HH_COLLECTION,
  GENERAL_SPOT_MULTISPECTRAL_4BANDS_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION,
  GENERAL_SPOT_PANCHROMATIC_COLLECTION,
  PRISM_GENERAL_WV3_MS4_OR_COLLECTION,
  PRISM_FRTX_WV3_PM4_OR_MS_COLLECTION,
  PRISM_FRTX_CSG_HIM_AB_HH_COLLECTION,
  FRTX_WORLDVIEW_4MS_COLLECTION,
  GENERAL_LEGION_PAN_COLLECTION,
  CSESA_GEOSAT_PSH_COLLECTION,
  FRTX_ICEYE_SLC_COG_VV_COLLECTION,
  PRISM_GENERAL_SAR_SCW_AB_HH_COLLECTION,
  PRISM_GENERAL_SAR_SM_SSC_HH_COLLECTION,
  PRISM_GENERAL_PHR_BUN_1A_MS_COLLECTION,
  PRISM_FRTX_CSG_S2C_AB_HH_COLLECTION,
  PRISM_GENERAL_NAO_PMS_3_COLLECTION,
  GENERAL_WORLDVIEW_4PS_COLLECTION,
  PRISM_GENERAL_PHR_BUN_1A_PAN_COLLECTION,
  PRISM_FRTX_PHR_BUN_3_PAN_COLLECTION,
  PRISM_GENERAL_SAR_SM_MGD_HH_COLLECTION,
  PRISM_FRTX_SKY_CPS_3P_COLLECTION,
  PRISM_GENERAL_WV3_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_WV1_MS4_OR_COLLECTION,
  GENERAL_PNEO_PANSHARPENED_4BANDS_COLLECTION,
  PRISM_FRTX_WV1_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_UF_SGF_HH_COLLECTION,
  PRISM_GENERAL_SAR_SLH_SL_VV_COLLECTION,
  PRISM_FRTX_WV3_PSH_OR_COLLECTION,
  GENERAL_SKYSAT_PAN_COLLECTION,
  FRTX_LEGION_PAN_COLLECTION,
  PRISM_FRTX_PHR_FUS_3_COLLECTION,
  PRISM_FRTX_PHR_BUN_3_MS_COLLECTION,
  PRISM_FRTX_WV6_PAN_SO_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION,
  PRISM_GENERAL_SAR_SM_MGD_HV_COLLECTION,
  PRISM_GENERAL_CSG_HIM_1B_HV_COLLECTION,
  CSESA_PLANETSCOPE_MS_4_COLLECTION,
  GENERAL_GEOSAT_PS3_COLLECTION,
  GENERAL_LEGION_4MS_COLLECTION,
  PRISM_GENERAL_SAR_XF_SLC_HH_COLLECTION,
  GENERAL_GEOSAT_MS4_COLLECTION,
];
