import { getVisualizationEffectsFromStore } from '../utils/effectsUtils';
import { getOrbitDirectionFromList } from '../Tools/VisualizationPanel/VisualizationPanel.utils';
import { selectActiveExternalLayer } from '../store/slices/externalLayersSlice';
import type { RootState } from '../hooks';

export const mapStoreToProps = (store: RootState) => {
  return {
    lat: store.mainMap.lat,
    lng: store.mainMap.lng,
    zoom: store.mainMap.zoom,
    mapBounds: store.mainMap.bounds,
    baseLayerId: store.mainMap.baseLayerId,
    enabledOverlaysId: store.mainMap.enabledOverlaysId,
    displayingSearchResults: store.searchResults.displayingSearchResults,
    searchResults: store.searchResults.searchResult?.allResults,
    RRDResults: store.resultsSection.results,
    currentPage: store.resultsSection.currentPage,
    RRDSortStateResultsSection: store.resultsSection.sortState,
    RRDFilterStateResultsSection: store.resultsSection.filterState,
    highlightedRRDResult: store.resultsSection.highlightedResult,
    highlightedTile: store.searchResults.highlightedTile,
    aoiGeometry: store.aoi.geometry,
    aoiBounds: store.aoi.bounds,
    aoiLastEdited: store.aoi.lastEdited,
    loiGeometry: store.loi.geometry,
    loiLastEdited: store.loi.lastEdited,
    displayTimelapseAreaPreview: store.timelapse.displayTimelapseAreaPreview,
    poiPosition: store.poi.position,
    poiLastEdited: store.poi.lastEdited,
    datasetId: store.visualization.datasetId,
    visibleOnMap: store.visualization.visibleOnMap,
    visualizationLayerId: store.visualization.layerId,
    visualizationUrl: store.visualization.visualizationUrl,
    fromTime: store.visualization.fromTime,
    toTime: store.visualization.toTime,
    customSelected: store.visualization.customSelected,
    evalscript: store.visualization.evalscript,
    evalscriptUrl: store.visualization.evalscriptUrl,
    dataFusion: store.visualization.dataFusion,
    cloudCoverage: store.visualization.cloudCoverage,
    selectedProcessing: store.visualization.selectedProcessing,
    processGraph: store.visualization.processGraph,
    dataSourcesInitialized: store.themes.dataSourcesInitialized,
    dataSourcesReadyVersion: store.themes.dataSourcesReadyVersion,
    selectedThemeId: store.themes.selectedThemeId,
    selectedTabIndex: store.tabs.selectedTabIndex,
    selectedLanguage: store.language.selectedLanguage,
    ...getVisualizationEffectsFromStore(store),
    orbitDirection: getOrbitDirectionFromList(store.visualization.orbitDirection),
    error: store.visualization.error,
    comparedLayers: store.compare.comparedLayers,
    comparedOpacity: store.compare.comparedOpacity,
    comparedClipping: store.compare.comparedClipping,
    auth: store.auth,
    is3D: store.mainMap.is3D,
    selectedModeId: store.themes.selectedModeId,
    elevationProfileHighlightedPoint: store.elevationProfile.highlightedPoint,
    quicklookOverlays: store.mainMap.quicklookOverlays,
    filteredQuicklookOverlays: store.mainMap.filteredQuicklookOverlays,
    activeExternalLayer: selectActiveExternalLayer(store),
    wmsPanelOpen: store.panel.wms,
  };
};
