export const COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_COLLECTION_IDS = {
  FLP: '3dd04866-fe0a-48f2-a07b-033350949919',
  FLPCL: 'f62789df-4e26-4469-85e5-9f3e464d98f7',
};

export const COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_LAYER_IDS = {
  FLP: 'Fallow Land Presence',
  FLPCL: 'Fallow Land Presence Confidence Layer',
};

export const COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_DATASET_IDENTIFIERS = {
  FLP: 'clms_vlcc_fallow-land-presence_europe_10m_yearly_v1',
  FLPCL: 'clms_vlcc_fallow-land-presence-confidence-layer_europe_10m_yearly_v1',
};

export const COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_LAYER_IDS.FLP]: COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_COLLECTION_IDS.FLP,
  [COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_LAYER_IDS.FLPCL]:
    COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_COLLECTION_IDS.FLPCL,
};

export const COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_LAYER_IDS.FLP]: ['CPFLP'],
  [COPERNICUS_CLMS_CPFLP_10M_YEARLY_V1_LAYER_IDS.FLPCL]: ['CPFLPCL'],
};

export const COPERNICUS_CLMS_DLT_10M_YEARLY_V1_COLLECTION_IDS = {
  DLT: '42b2ef44-5983-4bd1-9e2f-52c093c08b3d',
  DLTCL: '626dc954-9177-41f3-84c9-d2119402e524',
};

export const COPERNICUS_CLMS_DLT_10M_YEARLY_V1_LAYER_IDS = {
  DLT: 'Dominant Leaf Type',
  DLTCL: 'Dominant Leaf Type Confidence Layer',
};

export const COPERNICUS_CLMS_DLT_10M_YEARLY_V1_DATASET_IDENTIFIERS = {
  DLT: 'clms_vlcc_dominant-leaf-type_europe_10m_yearly_v1',
  DLTCL: 'clms_vlcc_dominant-leaf-type-confidence-layer_europe_10m_yearly_v1',
};

export const COPERNICUS_CLMS_DLT_10M_YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_DLT_10M_YEARLY_V1_LAYER_IDS.DLT]: COPERNICUS_CLMS_DLT_10M_YEARLY_V1_COLLECTION_IDS.DLT,
  [COPERNICUS_CLMS_DLT_10M_YEARLY_V1_LAYER_IDS.DLTCL]: COPERNICUS_CLMS_DLT_10M_YEARLY_V1_COLLECTION_IDS.DLTCL,
};

export const COPERNICUS_CLMS_DLT_10M_YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_DLT_10M_YEARLY_V1_LAYER_IDS.DLT]: ['DLT'],
  [COPERNICUS_CLMS_DLT_10M_YEARLY_V1_LAYER_IDS.DLTCL]: ['DLTCL'],
};

export const COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_COLLECTION_IDS = {
  CTY: '4fa71893-371f-4440-97c4-917f569f67b2',
  CTYCL: '82c292b4-1041-46c6-836a-4f7afe025d99',
};

export const COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_LAYER_IDS = {
  CTY: 'Crop Types',
  CTYCL: 'Crop Types Confidence Layer',
};

export const COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_DATASET_IDENTIFIERS = {
  CTY: 'clms_vlcc_crop-types_europe_10m_yearly_v1',
  CTYCL: 'clms_vlcc_crop-types-confidence-layer_europe_10m_yearly_v1',
};

export const COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_LAYER_IDS.CTY]:
    COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_COLLECTION_IDS.CTY,
  [COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_LAYER_IDS.CTYCL]:
    COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_COLLECTION_IDS.CTYCL,
};

export const COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_LAYER_IDS.CTY]: ['CTY'],
  [COPERNICUS_CLMS_VLCC_CROP_TYPES_EUROPE_10M_YEARLY_V1_LAYER_IDS.CTYCL]: ['CTYCL'],
};

export const COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_COLLECTION_IDS = {
  CPMCD: '0c1cf3ba-b04b-48c1-982f-e5861c0fdbd1',
  CPMCDCL: '1d4d9305-042a-4894-8a57-dfe93937a81a',
};

export const COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_LAYER_IDS = {
  CPMCD: 'Main Crop Duration',
  CPMCDCL: 'Main Crop Duration Confidence Layer',
};

export const COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_DATASET_IDENTIFIERS = {
  CPMCD: 'clms_vlcc_main-crop-duration_europe_10m_yearly_v1',
  CPMCDCL: 'clms_vlcc_main-crop-duration-confidence-layer_europe_10m_yearly_v1',
};

export const COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_LAYER_IDS.CPMCD]:
    COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_COLLECTION_IDS.CPMCD,
  [COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_LAYER_IDS.CPMCDCL]:
    COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_COLLECTION_IDS.CPMCDCL,
};

export const COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_LAYER_IDS.CPMCD]: ['CPMCD'],
  [COPERNICUS_CLMS_CPMCD_10M_YEARLY_V1_LAYER_IDS.CPMCDCL]: ['CPMCDCL'],
};

export const COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_COLLECTION_IDS = {
  TCPC: 'c1e547c2-47ec-4ce7-b87c-3057faba5ecc',
  TCPCCL: '86fea022-0a9a-44b1-81c6-61df8d508712',
};

export const COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_LAYER_IDS = {
  TCPC: 'Tree Cover Presence Change',
  TCPCCL: 'Tree Cover Presence Change Confidence Layer',
};

export const COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_DATASET_IDENTIFIERS = {
  TCPC: 'clms_vlcc_tree-cover-presence-change_europe_20m_3yearly_v1',
  TCPCCL: 'clms_vlcc_tree-cover-presence-change-confidence-layer_europe_20m_3yearly_v1',
};

export const COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_LAYER_IDS.TCPC]:
    COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_COLLECTION_IDS.TCPC,
  [COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_LAYER_IDS.TCPCCL]:
    COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_COLLECTION_IDS.TCPCCL,
};

export const COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_LAYER_IDS.TCPC]: ['TCPC'],
  [COPERNICUS_CLMS_VLCC_TCPC_20M_3YEARLY_V1_LAYER_IDS.TCPCCL]: ['TCPCCL'],
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_COLLECTION_IDS = {
  GRAC: '3f55450a-6912-4d68-a35b-b6dd331988e0',
  GRACCL: '16abb517-5c29-48ac-a97b-50be03a03a48',
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_LAYER_IDS = {
  GRAC: 'Grassland Change',
  GRACCL: 'Grassland Change Confidence Layer',
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_DATASET_IDENTIFIERS = {
  GRAC: 'clms_vlcc_grassland-change_europe_20m_3yearly_v1',
  GRACCL: 'clms_vlcc_grassland-change-confidence-layer_europe_20m_3yearly_v1',
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_LAYER_IDS.GRAC]:
    COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_COLLECTION_IDS.GRAC,
  [COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_LAYER_IDS.GRACCL]:
    COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_COLLECTION_IDS.GRACCL,
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_LAYER_IDS.GRAC]: ['GRAC'],
  [COPERNICUS_CLMS_VLCC_GRASSLAND_CHANGE_EUROPE_20M_3YEARLY_V1_LAYER_IDS.GRACCL]: ['GRACCL'],
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_COLLECTION_IDS = {
  GRA: '74eeaebb-d8eb-4e7e-909c-ab55465a8791',
  GRACL: '8a1883b3-5c43-4765-a02a-f95fe0231652',
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_LAYER_IDS = {
  GRA: 'Grassland',
  GRACL: 'Grassland Confidence Layer',
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_DATASET_IDENTIFIERS = {
  GRA: 'clms_vlcc_grassland_europe_10m_yearly_v1',
  GRACL: 'clms_vlcc_grassland-confidence-layer_europe_10m_yearly_v1',
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_LAYER_IDS.GRA]:
    COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_COLLECTION_IDS.GRA,
  [COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_LAYER_IDS.GRACL]:
    COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_COLLECTION_IDS.GRACL,
};

export const COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_LAYER_IDS.GRA]: ['GRA'],
  [COPERNICUS_CLMS_VLCC_GRASSLAND_EUROPE_10M_YEARLY_V1_LAYER_IDS.GRACL]: ['GRACL'],
};

export const COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_COLLECTION_IDS = {
  TCD: '3751d55a-7370-4071-9543-493ec3341d16',
  TCDCL: '2bdc627a-ea9c-4f34-81c2-75ad9d9cdbf1',
};

export const COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_LAYER_IDS = {
  TCD: 'Tree Cover Density',
  TCDCL: 'Tree Cover Density Confidence Layer',
};

export const COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_DATASET_IDENTIFIERS = {
  TCD: 'clms_vlcc_tree-cover-density_europe_10m_yearly_v1',
  TCDCL: 'clms_vlcc_tree-cover-density-confidence-layer_europe_10m_yearly_v1',
};

export const COPERNICUS_CLMS_DLTC_EUROPE_20M_3YEARLY_V1_DATASET_IDENTIFIER =
  'clms_vlcc_dominant-leaf-type-change_europe_20m_3yearly_v1';

export const COPERNICUS_CLMS_VLCC_FOREST_TYPE_EUROPE_10M_3YEARLY_V1_DATASET_IDENTIFIER =
  'clms_vlcc_forest-type_europe_10m_3yearly_v1';

export const COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_COLLECTION_ID_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_LAYER_IDS.TCD]:
    COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_COLLECTION_IDS.TCD,
  [COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_LAYER_IDS.TCDCL]:
    COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_COLLECTION_IDS.TCDCL,
};

export const COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_BANDS_BY_LAYER_ID = {
  [COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_LAYER_IDS.TCD]: ['TCD'],
  [COPERNICUS_CLMS_VLCC_TREE_COVER_DENSITY_EUROPE_10M_YEARLY_V1_LAYER_IDS.TCDCL]: ['TCDCL'],
};
