import { DATASOURCES } from '../../../const.js';
import {
  GENERAL_PNEO_PANCHROMATIC_COLLECTION,
  GENERAL_GEOSAT_MS4_COLLECTION,
  PRISM_FRTX_GIS_PM4_OR_MS_COLLECTION,
  PRISM_FRTX_WV1_PM4_OR_PAN_COLLECTION,
  PRISM_FRTX_GIS_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_SAR_HS_SSC_VV_COLLECTION,
  PRISM_GENERAL_SAR_HIM_AB_HH_COLLECTION,
  FRTX_ICEYE_GRD_COG_VV_COLLECTION,
  PRISM_GENERAL_CSG_HIM_1B_HV_COLLECTION,
  GENERAL_RADARSAT_SLC_VV_COLLECTION,
  GENERAL_RADARSAT_SGF_HV_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION,
  GENERAL_PNEO_PANSHARPENED_4BANDS_COLLECTION,
  PRISM_GENERAL_SAR_SLH_SL_VV_COLLECTION,
  PRISM_FRTX_WV3_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_NAO_MS_3_COLLECTION,
  GENERAL_SKYSAT_MS_4_COLLECTION,
  PRISM_GENERAL_SAR_HIM_AU_HH_COLLECTION,
  PRISM_FRTX_SKY_CPS_3P_COLLECTION,
  CSESA_GHGSAT_CH4_COLLECTION,
  PRISM_FRTX_PHR_BUN_3_PAN_COLLECTION,
  PRISM_GENERAL_SAR_UF_SGF_HH_COLLECTION,
  PRISM_GENERAL_WV1_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_GIS_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_WV1_PM4_SO_MS_COLLECTION,
  GENERAL_WORLDVIEW_4PS_COLLECTION,
  PRISM_GENERAL_WV1_PM4_OR_MS_COLLECTION,
  PRISM_FRTX_WV6_PAN_OR_COLLECTION,
  FRTX_GHGSAT_CH4_COLLECTION,
  CSESA_WORLDVIEW_8MS_COLLECTION,
  PRISM_GENERAL_SAR_SM_SSC_HH_COLLECTION,
  PRISM_GENERAL_PHR_MS_3_COLLECTION,
  PRISM_GENERAL_CSG_SC1_AB_HH_COLLECTION,
  FRTX_PNEO_PANSHARPENED_4BANDS_COLLECTION,
  GENERAL_GHGSAT_CH4_COLLECTION,
  PRISM_GENERAL_SAR_UW_SLC_HH_COLLECTION,
  GENERAL_SKYSAT_PAN_COLLECTION,
  PRISM_GENERAL_PHR_BUN_1A_PAN_COLLECTION,
  PRISM_FRTX_GIS_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_SM_MGD_HH_COLLECTION,
  PRISM_FRTX_PHR_FUS_3_COLLECTION,
  PRISM_GENERAL_WV3_PM4_OR_PAN_COLLECTION,
  PRISM_FRTX_WV3_PM4_SO_PAN_COLLECTION,
  GENERAL_PNEO_MULTISPECTRAL_6BANDS_COLLECTION,
  PRISM_GENERAL_WV1_PSH_OR_COLLECTION,
  PRISM_FRTX_WV3_PM4_OR_MS_COLLECTION,
  GENERAL_RADARSAT_SGF_HH_COLLECTION,
  PRISM_GENERAL_SAR_XF_SGF_HH_COLLECTION,
  PRISM_FRTX_CSG_HIM_AB_HH_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_GEC_SE_HH_COLLECTION,
  PRISM_GENERAL_SAR_HIM_1B_HH_COLLECTION,
  GENERAL_WORLDVIEW_4MS_COLLECTION,
  PRISM_FRTX_PHR_BUN_1A_MS_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION,
  PRISM_GENERAL_SAR_SCW_1B_HH_COLLECTION,
  GENERAL_PNEO_PANSHARPENED_COLLECTION,
  CSESA_WORLDVIEW_RGB_COLLECTION,
  PRISM_FRTX_WV3_PSH_OR_COLLECTION,
  GENERAL_PNEO_PANSHARPENED_6BANDS_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION,
  CSESA_WORLDVIEW_PAN_COLLECTION,
  PRISM_GENERAL_CSG_S2C_AB_HH_COLLECTION,
  GENERAL_LEGION_8MS_COLLECTION,
  PRISM_FRTX_SAR_ST_SSC_HH_COLLECTION,
  PRISM_FRTX_SAR_SM_SSC_HH_COLLECTION,
  GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION,
  PRISM_GENERAL_SAR_ST_SSC_HH_COLLECTION,
  PRISM_GENERAL_WV1_MS4_OR_COLLECTION,
  PRISM_GENERAL_PHR_BUN_1A_MS_COLLECTION,
  GENERAL_WORLDVIEW_RGB_COLLECTION,
  PRISM_GENERAL_GIS_PSH_OR_COLLECTION,
  PRISM_FRTX_WV6_PAN_SO_COLLECTION,
  PRISM_GENERAL_WV1_PM4_SO_PAN_COLLECTION,
  PRISM_FRTX_SAR_HS_SSC_VV_COLLECTION,
  GENERAL_LEGION_4PS_COLLECTION,
  GENERAL_PLANETSCOPE_MS_4_COLLECTION,
  PRISM_GENERAL_WV3_MS4_OR_COLLECTION,
  FRTX_LEGION_PAN_COLLECTION,
  GENERAL_WORLDVIEW_8MS_COLLECTION,
  GENERAL_PHR_PANSHARPENED_4BANDS_COLLECTION,
  CSESA_RADARSAT_SGF_HV_COLLECTION,
  GENERAL_GEOSAT_PAN_COLLECTION,
  PRISM_GENERAL_WV3_PM4_SO_MS_COLLECTION,
  PRISM_FRTX_DOV_MS_L3A_COLLECTION,
  PRISM_GENERAL_WV1_PM4_OR_PAN_COLLECTION,
  PRISM_GENERAL_PNE_PMS_3_COLLECTION,
  PRISM_GENERAL_GIS_PM4_SO_MS_COLLECTION,
  PRISM_GENERAL_PHR_FUS_3_COLLECTION,
  CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION,
  PRISM_FRTX_WV1_PM4_OR_MS_COLLECTION,
  GENERAL_ICEYE_SLC_COG_VV_COLLECTION,
  PRISM_GENERAL_SKY_CPS_3P_COLLECTION,
  PRISM_FRTX_PHR_BUN_3_MS_COLLECTION,
  PRISM_FRTX_GIS_PSH_OR_COLLECTION,
  GENERAL_ICEYE_GRD_COG_VV_COLLECTION,
  PRISM_GENERAL_SAR_HS_SSC_HH_VV_COLLECTION,
  CSESA_RADARSAT_SGF_HH_COLLECTION,
  PRISM_FRTX_PHR_BUN_1A_PAN_COLLECTION,
  PRISM_GENERAL_GIS_MS4_OR_COLLECTION,
  GENERAL_WORLDVIEW_PAN_COLLECTION,
  GENERAL_RADARSAT_SLC_HH_COLLECTION,
  GENERAL_SKYSAT_PANS_COLLECTION,
  PRISM_GENERAL_GIS_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_WX_SGF_HH_COLLECTION,
  PRISM_GENERAL_WV3_PM4_SO_PAN_COLLECTION,
  PRISM_GENERAL_SAR_SM_SSC_HH_HV_COLLECTION,
  PRISM_GENERAL_SAR_XF_SLC_HH_COLLECTION,
  PRISM_GENERAL_SAR_SC_MGD_VV_COLLECTION,
  PRISM_FRTX_SAR_SLH_SL_VV_COLLECTION,
  GENERAL_GEOSAT_PSH_COLLECTION,
  PRISM_GENERAL_DOV_MS_L3A_COLLECTION,
  CSESA_WORLDVIEW_4PS_COLLECTION,
  PRISM_FRTX_SAR_SP2_AB_VV_COLLECTION,
  GENERAL_ICEYE_TEST_VV_COLLECTION,
  CSESA_SKYSAT_MS_4_COLLECTION,
  PRISM_GENERAL_CSG_HIM_1B_HH_COLLECTION,
  CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION,
  PRISM_FRTX_WV3_PSH_SO_COLLECTION,
  PRISM_GENERAL_SAR_SC_MGD_HH_COLLECTION,
  PRISM_GENERAL_NAO_PMS_3_COLLECTION,
  GENERAL_RADARSAT_SLC_VH_COLLECTION,
  PRISM_GENERAL_SAR_SM_GR_VV_COLLECTION,
  CSESA_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION,
  PRISM_GENERAL_SAR_UW_SGF_HH_COLLECTION,
  GENERAL_PLANETSCOPE_MS_8_COLLECTION,
  PRISM_GENERAL_WV3_PSH_OR_COLLECTION,
  GENERAL_GEOSAT_PS3_COLLECTION,
  GENERAL_PAZ_GEC_RE_HH_COLLECTION,
  PRISM_GENERAL_CSG_SC1_1B_HH_COLLECTION,
  PRISM_GENERAL_WV3_PM4_OR_MS_COLLECTION,
  PRISM_GENERAL_SAR_SP2_AB_VV_COLLECTION,
  PRISM_GENERAL_HRS_PSH_1C_COLLECTION,
  PRISM_GENERAL_SAR_SCW_1B_VV_COLLECTION,
  PRISM_FRTX_WV3_PM4_SO_MS_COLLECTION,
  PRISM_GENERAL_SAR_SM_MGD_HV_COLLECTION,
  PRISM_GENERAL_CSG_HIM_AB_HH_COLLECTION,
  PRISM_FRTX_WV1_PM4_SO_PAN_COLLECTION,
  GENERAL_LEGION_PAN_COLLECTION,
  CSESA_WORLDVIEW_4MS_COLLECTION,
  GENERAL_PHR_PANCHROMATIC_COLLECTION,
  PRISM_GENERAL_SAR_SCW_AB_HH_COLLECTION,
  GENERAL_LEGION_4MS_COLLECTION,
  GENERAL_PHR_MULTISPECTRAL_4BANDS_COLLECTION,
  PRISM_FRTX_CSG_S2C_AB_HH_COLLECTION,
} from './RRDDataSources/dataSourceRRDConstants';

export function datasourceForRRDDatasetId(datasetId) {
  switch (datasetId) {
    case GENERAL_PNEO_PANCHROMATIC_COLLECTION:
    case GENERAL_PNEO_PANSHARPENED_4BANDS_COLLECTION:
    case FRTX_PNEO_PANSHARPENED_4BANDS_COLLECTION:
    case GENERAL_PNEO_MULTISPECTRAL_6BANDS_COLLECTION:
    case GENERAL_PNEO_PANSHARPENED_COLLECTION:
    case GENERAL_PNEO_PANSHARPENED_6BANDS_COLLECTION:
    case PRISM_GENERAL_PNE_PMS_3_COLLECTION:
      return DATASOURCES.RRD_AIRBUS_FE_PLEIADAS_NEO;
    case GENERAL_GEOSAT_MS4_COLLECTION:
    case GENERAL_GEOSAT_PAN_COLLECTION:
    case GENERAL_GEOSAT_PSH_COLLECTION:
    case GENERAL_GEOSAT_PS3_COLLECTION:
    case PRISM_GENERAL_HRS_PSH_1C_COLLECTION:
      return DATASOURCES.RRD_GEOSAT;
    case PRISM_FRTX_GIS_PM4_OR_MS_COLLECTION:
    case PRISM_FRTX_WV1_PM4_OR_PAN_COLLECTION:
    case PRISM_FRTX_GIS_PM4_OR_PAN_COLLECTION:
    case PRISM_FRTX_WV3_PM4_OR_PAN_COLLECTION:
    case PRISM_GENERAL_WV1_PM4_SO_MS_COLLECTION:
    case PRISM_FRTX_GIS_PM4_SO_MS_COLLECTION:
    case PRISM_FRTX_WV1_PM4_SO_MS_COLLECTION:
    case GENERAL_WORLDVIEW_4PS_COLLECTION:
    case PRISM_GENERAL_WV1_PM4_OR_MS_COLLECTION:
    case PRISM_FRTX_WV6_PAN_OR_COLLECTION:
    case CSESA_WORLDVIEW_8MS_COLLECTION:
    case PRISM_FRTX_GIS_PM4_SO_PAN_COLLECTION:
    case PRISM_GENERAL_WV3_PM4_OR_PAN_COLLECTION:
    case PRISM_FRTX_WV3_PM4_SO_PAN_COLLECTION:
    case PRISM_GENERAL_WV1_PSH_OR_COLLECTION:
    case PRISM_FRTX_WV3_PM4_OR_MS_COLLECTION:
    case GENERAL_WORLDVIEW_4MS_COLLECTION:
    case CSESA_WORLDVIEW_RGB_COLLECTION:
    case PRISM_FRTX_WV3_PSH_OR_COLLECTION:
    case CSESA_WORLDVIEW_PAN_COLLECTION:
    case GENERAL_LEGION_8MS_COLLECTION:
    case PRISM_GENERAL_WV1_MS4_OR_COLLECTION:
    case GENERAL_WORLDVIEW_RGB_COLLECTION:
    case PRISM_GENERAL_GIS_PSH_OR_COLLECTION:
    case PRISM_FRTX_WV6_PAN_SO_COLLECTION:
    case PRISM_GENERAL_WV1_PM4_SO_PAN_COLLECTION:
    case GENERAL_LEGION_4PS_COLLECTION:
    case PRISM_GENERAL_WV3_MS4_OR_COLLECTION:
    case FRTX_LEGION_PAN_COLLECTION:
    case GENERAL_WORLDVIEW_8MS_COLLECTION:
    case PRISM_GENERAL_WV3_PM4_SO_MS_COLLECTION:
    case PRISM_GENERAL_WV1_PM4_OR_PAN_COLLECTION:
    case PRISM_GENERAL_GIS_PM4_SO_MS_COLLECTION:
    case PRISM_FRTX_WV1_PM4_OR_MS_COLLECTION:
    case PRISM_FRTX_GIS_PSH_OR_COLLECTION:
    case PRISM_GENERAL_GIS_MS4_OR_COLLECTION:
    case GENERAL_WORLDVIEW_PAN_COLLECTION:
    case PRISM_GENERAL_GIS_PM4_SO_PAN_COLLECTION:
    case PRISM_GENERAL_WV3_PM4_SO_PAN_COLLECTION:
    case CSESA_WORLDVIEW_4PS_COLLECTION:
    case PRISM_FRTX_WV3_PSH_SO_COLLECTION:
    case PRISM_GENERAL_WV3_PSH_OR_COLLECTION:
    case PRISM_GENERAL_WV3_PM4_OR_MS_COLLECTION:
    case PRISM_FRTX_WV3_PM4_SO_MS_COLLECTION:
    case PRISM_FRTX_WV1_PM4_SO_PAN_COLLECTION:
    case GENERAL_LEGION_PAN_COLLECTION:
    case CSESA_WORLDVIEW_4MS_COLLECTION:
    case GENERAL_LEGION_4MS_COLLECTION:
      return DATASOURCES.RRD_EUSI;
    case PRISM_GENERAL_SAR_HS_SSC_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SM_SSC_HH_COLLECTION:
    case PRISM_GENERAL_SAR_SM_MGD_HH_COLLECTION:
    case GENERAL_TERRASAR_X_TANDEM_X_GEC_SE_HH_COLLECTION:
    case GENERAL_TERRASAR_X_TANDEM_X_GEC_RE_HH_COLLECTION:
    case PRISM_FRTX_SAR_ST_SSC_HH_COLLECTION:
    case PRISM_FRTX_SAR_SM_SSC_HH_COLLECTION:
    case PRISM_GENERAL_SAR_ST_SSC_HH_COLLECTION:
    case PRISM_FRTX_SAR_HS_SSC_VV_COLLECTION:
    case PRISM_GENERAL_SAR_HS_SSC_HH_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SM_SSC_HH_HV_COLLECTION:
    case PRISM_GENERAL_SAR_SC_MGD_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SC_MGD_HH_COLLECTION:
    case GENERAL_PAZ_GEC_RE_HH_COLLECTION:
    case PRISM_GENERAL_SAR_SM_MGD_HV_COLLECTION:
      return DATASOURCES.RRD_PAZ;
    case PRISM_GENERAL_SAR_HIM_AB_HH_COLLECTION:
    case PRISM_GENERAL_SAR_HIM_AU_HH_COLLECTION:
    case PRISM_GENERAL_SAR_HIM_1B_HH_COLLECTION:
    case PRISM_GENERAL_SAR_SCW_1B_HH_COLLECTION:
    case PRISM_FRTX_SAR_SP2_AB_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SP2_AB_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SCW_1B_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SCW_AB_HH_COLLECTION:
      return DATASOURCES.RRD_SKYMED_1;
    case FRTX_ICEYE_GRD_COG_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SLH_SL_VV_COLLECTION:
    case GENERAL_ICEYE_SLC_COG_VV_COLLECTION:
    case GENERAL_ICEYE_GRD_COG_VV_COLLECTION:
    case PRISM_FRTX_SAR_SLH_SL_VV_COLLECTION:
    case GENERAL_ICEYE_TEST_VV_COLLECTION:
    case PRISM_GENERAL_SAR_SM_GR_VV_COLLECTION:
      return DATASOURCES.RRD_ICEYE;
    case PRISM_GENERAL_CSG_HIM_1B_HV_COLLECTION:
    case PRISM_GENERAL_CSG_SC1_AB_HH_COLLECTION:
    case PRISM_FRTX_CSG_HIM_AB_HH_COLLECTION:
    case PRISM_GENERAL_CSG_S2C_AB_HH_COLLECTION:
    case PRISM_GENERAL_CSG_HIM_1B_HH_COLLECTION:
    case PRISM_GENERAL_CSG_SC1_1B_HH_COLLECTION:
    case PRISM_GENERAL_CSG_HIM_AB_HH_COLLECTION:
    case PRISM_FRTX_CSG_S2C_AB_HH_COLLECTION:
      return DATASOURCES.RRD_SKYMED_2;
    case GENERAL_RADARSAT_SLC_VV_COLLECTION:
    case GENERAL_RADARSAT_SGF_HV_COLLECTION:
    case PRISM_GENERAL_SAR_UF_SGF_HH_COLLECTION:
    case PRISM_GENERAL_SAR_UW_SLC_HH_COLLECTION:
    case GENERAL_RADARSAT_SGF_HH_COLLECTION:
    case PRISM_GENERAL_SAR_XF_SGF_HH_COLLECTION:
    case CSESA_RADARSAT_SGF_HV_COLLECTION:
    case CSESA_RADARSAT_SGF_HH_COLLECTION:
    case GENERAL_RADARSAT_SLC_HH_COLLECTION:
    case PRISM_GENERAL_SAR_WX_SGF_HH_COLLECTION:
    case PRISM_GENERAL_SAR_XF_SLC_HH_COLLECTION:
    case GENERAL_RADARSAT_SLC_VH_COLLECTION:
    case PRISM_GENERAL_SAR_UW_SGF_HH_COLLECTION:
      return DATASOURCES.RRD_RADARSAT2;
    case GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION:
    case GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION:
    case GENERAL_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION:
    case CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VV_COLLECTION:
    case CSESA_TERRASAR_X_TANDEM_X_EEC_RE_VH_COLLECTION:
    case CSESA_TERRASAR_X_TANDEM_X_EEC_RE_HH_COLLECTION:
      return DATASOURCES.RRD_AIRBUS_DE;
    case PRISM_GENERAL_NAO_MS_3_COLLECTION:
    case PRISM_GENERAL_NAO_PMS_3_COLLECTION:
      return DATASOURCES.RRD_AIRBUS_FE_SPOT;
    case GENERAL_SKYSAT_MS_4_COLLECTION:
    case PRISM_FRTX_SKY_CPS_3P_COLLECTION:
    case GENERAL_SKYSAT_PAN_COLLECTION:
    case PRISM_GENERAL_SKY_CPS_3P_COLLECTION:
    case GENERAL_SKYSAT_PANS_COLLECTION:
    case CSESA_SKYSAT_MS_4_COLLECTION:
      return DATASOURCES.RRD_SKYSAT;
    case CSESA_GHGSAT_CH4_COLLECTION:
    case FRTX_GHGSAT_CH4_COLLECTION:
    case GENERAL_GHGSAT_CH4_COLLECTION:
      return DATASOURCES.RRD_GHGSAT;
    case PRISM_FRTX_PHR_BUN_3_PAN_COLLECTION:
    case PRISM_GENERAL_PHR_MS_3_COLLECTION:
    case PRISM_GENERAL_PHR_BUN_1A_PAN_COLLECTION:
    case PRISM_FRTX_PHR_FUS_3_COLLECTION:
    case PRISM_FRTX_PHR_BUN_1A_MS_COLLECTION:
    case PRISM_GENERAL_PHR_BUN_1A_MS_COLLECTION:
    case GENERAL_PHR_PANSHARPENED_4BANDS_COLLECTION:
    case PRISM_GENERAL_PHR_FUS_3_COLLECTION:
    case PRISM_FRTX_PHR_BUN_3_MS_COLLECTION:
    case PRISM_FRTX_PHR_BUN_1A_PAN_COLLECTION:
    case GENERAL_PHR_PANCHROMATIC_COLLECTION:
    case GENERAL_PHR_MULTISPECTRAL_4BANDS_COLLECTION:
      return DATASOURCES.RRD_AIRBUS_FE_PLEIADAS;
    case GENERAL_PLANETSCOPE_MS_4_COLLECTION:
    case PRISM_FRTX_DOV_MS_L3A_COLLECTION:
    case PRISM_GENERAL_DOV_MS_L3A_COLLECTION:
    case GENERAL_PLANETSCOPE_MS_8_COLLECTION:
      return DATASOURCES.RRD_PLANET_SCOPE;
    default:
      return null;
  }
}
