// --- Band units ---

const KELVIN = 'Kelvin';
const REFLECTANCE = 'Reflectance';
export const BAND_UNIT = {
  KELVIN,
  REFLECTANCE,
} as const;

// --- Sentinel-1 ---

export const S1 = 'S1';
export const S1_CDAS_IW_VVVH = 'S1_CDAS_IW_VVVH';
export const S1_CDAS_IW_HHHV = 'S1_CDAS_IW_HHHV';
export const S1_CDAS_IW_VV = 'S1_CDAS_IW_VV';
export const S1_CDAS_IW_HH = 'S1_CDAS_IW_HH';
export const S1_CDAS_EW_HHHV = 'S1_CDAS_EW_HHHV';
export const S1_CDAS_EW_VVVH = 'S1_CDAS_EW_VVVH';
export const S1_CDAS_EW_HH = 'S1_CDAS_EW_HH';
export const S1_CDAS_EW_VV = 'S1_CDAS_EW_VV';
export const S1_CDAS_SM_VVVH = 'S1_CDAS_SM_VVVH';
export const S1_CDAS_SM_VV = 'S1_CDAS_SM_VV';
export const S1_CDAS_SM_HHHV = 'S1_CDAS_SM_HHHV';
export const S1_CDAS_SM_HH = 'S1_CDAS_SM_HH';

// --- Sentinel-2 ---

export const S2_L1C_CDAS = 'S2_L1C_CDAS';
export const S2_L2A_CDAS = 'S2_L2A_CDAS';

// --- Sentinel-3 ---

export const S3SLSTR_CDAS = 'S3SLSTR_CDAS';
export const S3OLCI_CDAS = 'S3OLCI_CDAS';
export const S3OLCIL2_WATER = 'S3OLCIL2_WATER';
export const S3OLCIL2_LAND = 'S3OLCIL2_LAND';
export const S3SYNERGY_L2_AOD = 'S3SYNERGY_L2_AOD';
export const S3SYNERGY_L2_SYN = 'S3SYNERGY_L2_SYN';
export const S3SYNERGY_L2_VGP = 'S3SYNERGY_L2_VGP';
export const S3SYNERGY_L2_VG1 = 'S3SYNERGY_L2_VG1';
export const S3SYNERGY_L2_V10 = 'S3SYNERGY_L2_V10';

// --- Sentinel-5P ---

export const S5_O3_CDAS = 'S5_O3_CDAS';
export const S5_NO2_CDAS = 'S5_NO2_CDAS';
export const S5_SO2_CDAS = 'S5_SO2_CDAS';
export const S5_CO_CDAS = 'S5_CO_CDAS';
export const S5_HCHO_CDAS = 'S5_HCHO_CDAS';
export const S5_CH4_CDAS = 'S5_CH4_CDAS';
export const S5_AER_AI_CDAS = 'S5_AER_AI_CDAS';
export const S5_CLOUD_CDAS = 'S5_CLOUD_CDAS';
export const S5_OTHER_CDAS = 'S5_OTHER_CDAS';

// --- Landsat ---

export const CDAS_L8_L9_LOTL1 = 'CDAS_L8_L9_LOTL1';
export const CDAS_LANDSAT_MOSAIC = 'CDAS_LANDSAT_MOSAIC';

// --- DEM ---

export const DEM_MAPZEN = 'DEM_MAPZEN';
export const DEM_COPERNICUS_30 = 'DEM_COPERNICUS_30';
export const DEM_COPERNICUS_90 = 'DEM_COPERNICUS_90';
export const DEM_COPERNICUS_30_CDAS = 'DEM_COPERNICUS_30_CDAS';
export const DEM_COPERNICUS_90_CDAS = 'DEM_COPERNICUS_90_CDAS';

// --- Custom / BYOC ---

export const CUSTOM = 'CUSTOM';

// --- Mosaics ---

export const COPERNICUS_WORLDCOVER_ANNUAL_CLOUDLESS_MOSAIC = '65d4af89-5ce5-468e-bbbe-8a2fd9efaccc';
export const COPERNICUS_WORLDCOVER_QUARTERLY_CLOUDLESS_MOSAIC = '5460de54-082e-473a-b6ea-d5cbe3c17cca';
export const S1_MONTHLY_MOSAIC_DH = 'cc676fec-cb8d-4bc1-adce-1d9658da950b';
export const S1_MONTHLY_MOSAIC_IW = '3c662330-108b-4378-8899-525fd5a225cb';
export const S1_MONTHLY_MOSAIC_DH_LR = 'dd2837a1-8b59-46cf-ac58-3df2a3559803';
export const S1_MONTHLY_MOSAIC_IW_LR = 'b4d63c63-7572-4277-8f4a-aa3d672820db';

// --- CCM ---

export const CDSE_CCM_VHR_IMAGE_2018_COLLECTION = 'CCM_VHR_IMAGE_2018';
export const CDSE_CCM_VHR_IMAGE_2021_COLLECTION = 'CCM_VHR_IMAGE_2021';
export const CDSE_CCM_VHR_IMAGE_2024_COLLECTION = 'CCM_VHR_IMAGE_2024';

// --- CLMS ---

export const COPERNICUS_CLMS_VEGETATION_INDICES_NDVI_GLOBAL =
  'COPERNICUS_CLMS_VEGETATION_INDICES_NDVI_GLOBAL';
export const COPERNICUS_CLMS_BURNT_AREA_DAILY = 'COPERNICUS_CLMS_BURNT_AREA_DAILY';
export const COPERNICUS_CLMS_BURNT_AREA_MONTHLY = 'COPERNICUS_CLMS_BURNT_AREA_MONTHLY';
export const COPERNICUS_CLMS_BURNT_AREA_DAILY_V4 = 'COPERNICUS_CLMS_BURNT_AREA_DAILY_V4';
export const COPERNICUS_CLMS_BURNT_AREA_MONTHLY_V4 = 'COPERNICUS_CLMS_BURNT_AREA_MONTHLY_V4';
export const COPERNICUS_CLMS_DMP_1KM_10DAILY = 'COPERNICUS_CLMS_DMP_1KM_10DAILY';
export const COPERNICUS_CLMS_DMP_1KM_10DAILY_RT0 = 'COPERNICUS_CLMS_DMP_1KM_10DAILY_RT0';
export const COPERNICUS_CLMS_DMP_1KM_10DAILY_RT1 = 'COPERNICUS_CLMS_DMP_1KM_10DAILY_RT1';
export const COPERNICUS_CLMS_DMP_1KM_10DAILY_RT2 = 'COPERNICUS_CLMS_DMP_1KM_10DAILY_RT2';
export const COPERNICUS_CLMS_DMP_1KM_10DAILY_RT6 = 'COPERNICUS_CLMS_DMP_1KM_10DAILY_RT6';
export const COPERNICUS_CLMS_FAPAR_1KM_10DAILY = 'COPERNICUS_CLMS_FAPAR_1KM_10DAILY';
export const COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT0 = 'COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT0';
export const COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT1 = 'COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT1';
export const COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT2 = 'COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT2';
export const COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT6 = 'COPERNICUS_CLMS_FAPAR_1KM_10DAILY_RT6';
export const COPERNICUS_CLMS_LAI_1KM_10DAILY = 'COPERNICUS_CLMS_LAI_1KM_10DAILY';
export const COPERNICUS_CLMS_LAI_1KM_10DAILY_RT0 = 'COPERNICUS_CLMS_LAI_1KM_10DAILY_RT0';
export const COPERNICUS_CLMS_LAI_1KM_10DAILY_RT1 = 'COPERNICUS_CLMS_LAI_1KM_10DAILY_RT1';
export const COPERNICUS_CLMS_LAI_1KM_10DAILY_RT2 = 'COPERNICUS_CLMS_LAI_1KM_10DAILY_RT2';
export const COPERNICUS_CLMS_LAI_1KM_10DAILY_RT6 = 'COPERNICUS_CLMS_LAI_1KM_10DAILY_RT6';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT0 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT0';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT1 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT1';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT2 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT2';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT6 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_RT6';
export const COPERNICUS_CLMS_FCOVER_1KM_10DAILY = 'COPERNICUS_CLMS_FCOVER_1KM_10DAILY';
export const COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT0 = 'COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT0';
export const COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT1 = 'COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT1';
export const COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT2 = 'COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT2';
export const COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT6 = 'COPERNICUS_CLMS_FCOVER_1KM_10DAILY_RT6';
export const COPERNICUS_CLMS_FCOVER_300M_10DAILY = 'COPERNICUS_CLMS_FCOVER_300M_10DAILY';
export const COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT0 = 'COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT0';
export const COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT1 = 'COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT1';
export const COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT2 = 'COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT2';
export const COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT6 = 'COPERNICUS_CLMS_FCOVER_300M_10DAILY_RT6';
export const COPERNICUS_CLMS_GPP_300M_10DAILY_RT0 = 'COPERNICUS_CLMS_GPP_300M_10DAILY_RT0';
export const COPERNICUS_CLMS_GPP_300M_10DAILY_RT1 = 'COPERNICUS_CLMS_GPP_300M_10DAILY_RT1';
export const COPERNICUS_CLMS_GPP_300M_10DAILY_RT2 = 'COPERNICUS_CLMS_GPP_300M_10DAILY_RT2';
export const COPERNICUS_CLMS_GPP_300M_10DAILY_RT6 = 'COPERNICUS_CLMS_GPP_300M_10DAILY_RT6';
export const COPERNICUS_CLMS_LAI_300M_10DAILY = 'COPERNICUS_CLMS_LAI_300M_10DAILY';
export const COPERNICUS_CLMS_LAI_300M_10DAILY_RT0 = 'COPERNICUS_CLMS_LAI_300M_10DAILY_RT0';
export const COPERNICUS_CLMS_LAI_300M_10DAILY_RT1 = 'COPERNICUS_CLMS_LAI_300M_10DAILY_RT1';
export const COPERNICUS_CLMS_LAI_300M_10DAILY_RT2 = 'COPERNICUS_CLMS_LAI_300M_10DAILY_RT2';
export const COPERNICUS_CLMS_LAI_300M_10DAILY_RT6 = 'COPERNICUS_CLMS_LAI_300M_10DAILY_RT6';
export const COPERNICUS_CLMS_NPP_300M_10DAILY_RT0 = 'COPERNICUS_CLMS_NPP_300M_10DAILY_RT0';
export const COPERNICUS_CLMS_NPP_300M_10DAILY_RT1 = 'COPERNICUS_CLMS_NPP_300M_10DAILY_RT1';
export const COPERNICUS_CLMS_NPP_300M_10DAILY_RT2 = 'COPERNICUS_CLMS_NPP_300M_10DAILY_RT2';
export const COPERNICUS_CLMS_NPP_300M_10DAILY_RT6 = 'COPERNICUS_CLMS_NPP_300M_10DAILY_RT6';
export const COPERNICUS_CLMS_SWI_12_5KM_10DAILY = 'COPERNICUS_CLMS_SWI_12_5KM_10DAILY';
export const COPERNICUS_CLMS_SWI_12_5KM_DAILY = 'COPERNICUS_CLMS_SWI_12_5KM_DAILY';
export const COPERNICUS_CLMS_SWI_1KM_DAILY = 'COPERNICUS_CLMS_SWI_1KM_DAILY';
export const COPERNICUS_CLMS_DMP_300M_10DAILY_RT0 = 'COPERNICUS_CLMS_DMP_300M_10DAILY_RT0';
export const COPERNICUS_CLMS_DMP_300M_10DAILY_RT1 = 'COPERNICUS_CLMS_DMP_300M_10DAILY_RT1';
export const COPERNICUS_CLMS_DMP_300M_10DAILY_RT2 = 'COPERNICUS_CLMS_DMP_300M_10DAILY_RT2';
export const COPERNICUS_CLMS_DMP_300M_10DAILY_RT5 = 'COPERNICUS_CLMS_DMP_300M_10DAILY_RT5';
export const COPERNICUS_CLMS_DMP_300M_10DAILY_RT6 = 'COPERNICUS_CLMS_DMP_300M_10DAILY_RT6';
export const COPERNICUS_CLMS_LST_5KM_10DAILY_V1 = 'COPERNICUS_CLMS_LST_5KM_10DAILY_V1';
export const COPERNICUS_CLMS_LST_5KM_10DAILY_V2 = 'COPERNICUS_CLMS_LST_5KM_10DAILY_V2';
export const COPERNICUS_CLMS_NDVI_1KM_STATS_V2 = 'COPERNICUS_CLMS_NDVI_1KM_STATS_V2';
export const COPERNICUS_CLMS_NDVI_1KM_STATS_V3 = 'COPERNICUS_CLMS_NDVI_1KM_STATS_V3';
export const COPERNICUS_CLMS_NDVI_1KM_10DAILY_V2 = 'COPERNICUS_CLMS_NDVI_1KM_10DAILY_V2';
export const COPERNICUS_CLMS_NDVI_300M_10DAILY_V1 = 'COPERNICUS_CLMS_NDVI_300M_10DAILY_V1';
export const COPERNICUS_CLMS_NDVI_300M_10DAILY_V2 = 'COPERNICUS_CLMS_NDVI_300M_10DAILY_V2';
export const COPERNICUS_CLMS_NDVI_300M_10DAILY_V3 = 'COPERNICUS_CLMS_NDVI_300M_10DAILY_V3';
export const COPERNICUS_CLMS_SSM_1KM_DAILY_V1 = 'COPERNICUS_CLMS_SSM_1KM_DAILY_V1';
export const COPERNICUS_CLMS_LSP_300M_YEARLY_V1 = 'COPERNICUS_CLMS_LSP_300M_YEARLY_V1';
export const COPERNICUS_CLMS_LSP_300M_YEARLY_V2 = 'COPERNICUS_CLMS_LSP_300M_YEARLY_V2';
export const COPERNICUS_CLMS_LCC_100M_YEARLY_V3 = 'COPERNICUS_CLMS_LCC_100M_YEARLY_V3';
export const COPERNICUS_CLMS_LST_5KM_HOURLY_V1 = 'COPERNICUS_CLMS_LST_5KM_HOURLY_V1';
export const COPERNICUS_CLMS_LST_5KM_HOURLY_V2 = 'COPERNICUS_CLMS_LST_5KM_HOURLY_V2';
export const COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2 = 'COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2';
export const COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT0 = 'COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT1 = 'COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT2 = 'COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT6 = 'COPERNICUS_CLMS_GDMP_1KM_10DAILY_V2_RT6';
export const COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT0 = 'COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT0';
export const COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT1 = 'COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT1';
export const COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT2 = 'COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT2';
export const COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT5 = 'COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT5';
export const COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT6 = 'COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT6';
export const COPERNICUS_CLMS_WB_300M_10DAILY_V1 = 'COPERNICUS_CLMS_WB_300M_10DAILY_V1';
export const COPERNICUS_CLMS_WB_1KM_10DAILY_V2 = 'COPERNICUS_CLMS_WB_1KM_10DAILY_V2';
export const COPERNICUS_CLMS_WB_300M_MONTHLY_V2 = 'COPERNICUS_CLMS_WB_300M_MONTHLY_V2';
export const COPERNICUS_CLMS_SWE_5KM_DAILY_V1 = 'COPERNICUS_CLMS_SWE_5KM_DAILY_V1';
export const COPERNICUS_CLMS_SWE_5KM_DAILY_V2 = 'COPERNICUS_CLMS_SWE_5KM_DAILY_V2';
export const COPERNICUS_CLMS_SCE_EUROPE_500M_DAILY_V1 = 'COPERNICUS_CLMS_SCE_EUROPE_500M_DAILY_V1';
export const COPERNICUS_CLMS_SCE_NH_1KM_DAILY_V1 = 'COPERNICUS_CLMS_SCE_NH_1KM_DAILY_V1';
export const COPERNICUS_CLMS_SCE_GLOBAL_1KM_DAILY_V1 = 'COPERNICUS_CLMS_SCE_GLOBAL_1KM_DAILY_V1';
export const COPERNICUS_CLMS_LIE_500M_DAILY_V1 = 'COPERNICUS_CLMS_LIE_500M_DAILY_V1';
export const COPERNICUS_CLMS_LIE_250M_DAILY_V2 = 'COPERNICUS_CLMS_LIE_250M_DAILY_V2';
export const COPERNICUS_CLMS_WB_100M_MONTHLY_V1 = 'COPERNICUS_CLMS_WB_100M_MONTHLY_V1';
export const COPERNICUS_CLMS_LST_5KM_10DAILY_DAILY_CYCLE_V1 =
  'COPERNICUS_CLMS_LST_5KM_10DAILY_DAILY_CYCLE_V1';
export const COPERNICUS_CLMS_LST_5KM_10DAILY_DAILY_CYCLE_V2 =
  'COPERNICUS_CLMS_LST_5KM_10DAILY_DAILY_CYCLE_V2';
export const COPERNICUS_CLMS_LWQ_300M_10DAILY_NRT_V2 = 'COPERNICUS_CLMS_LWQ_300M_10DAILY_NRT_V2';
export const COPERNICUS_CLMS_LWQ_300M_10DAILY_REPROC_V1 = 'COPERNICUS_CLMS_LWQ_300M_10DAILY_REPROC_V1';
export const COPERNICUS_CLMS_LWQ_300M_10DAILY_NRT_V1 = 'COPERNICUS_CLMS_LWQ_300M_10DAILY_NRT_V1';
export const COPERNICUS_CLMS_LWQ_100M_10DAILY_NRT_V1 = 'COPERNICUS_CLMS_LWQ_100M_10DAILY_NRT_V1';
export const COPERNICUS_CLMS_LCM_10M_YEARLY_V1 = '828f6b20-8ffd-48f8-a1da-fefd271456db'; // needs to be actual collectionId so we can swap to low resolution collection
export const COPERNICUS_CLMS_TCD_10M_YEARLY_V1 = '8bd33a42-dce4-4554-9a1f-1bb248b4183d'; // needs to be actual collectionId so we can swap to low resolution collection
export const COPERNICUS_CLMS_LIE_500M_DAILY_V2 = 'COPERNICUS_CLMS_LIE_500M_DAILY_V2';
export const COPERNICUS_CLMS_SWI_12_5KM_DAILY_V4 = 'COPERNICUS_CLMS_SWI_12_5KM_DAILY_V4';
export const COPERNICUS_CLMS_SWI_1KM_DAILY_V2 = 'COPERNICUS_CLMS_SWI_1KM_DAILY_V2';
export const COPERNICUS_CLMS_SWI_12_5KM_10DAILY_V4 = 'COPERNICUS_CLMS_SWI_12_5KM_10DAILY_V4';
export const COPERNICUS_CLMS_LIE_BALTIC_250M_DAILY_V1 = 'COPERNICUS_CLMS_LIE_BALTIC_250M_DAILY_V1';
export const COPERNICUS_CLMS_ETA_GLOBAL_300M_10DAILY_V1 = 'COPERNICUS_CLMS_ETA_GLOBAL_300M_10DAILY_V1';
export const COPERNICUS_CLMS_HF_GLOBAL_300M_DAILY_V1 = 'COPERNICUS_CLMS_HF_GLOBAL_300M_DAILY_V1';
export const COPERNICUS_CLMS_LSWT_OFFLINE_1KM_10DAILY_V1 = 'COPERNICUS_CLMS_LSWT_OFFLINE_1KM_10DAILY_V1';
export const COPERNICUS_CLMS_LSWT_NRT_GLOBAL_1KM_10DAILY_V1 =
  'COPERNICUS_CLMS_LSWT_NRT_GLOBAL_1KM_10DAILY_V1';
export const COPERNICUS_CLMS_LWQ_NRT_GLOBAL_100M_10DAILY_V2 =
  'COPERNICUS_CLMS_LWQ_NRT_GLOBAL_100M_10DAILY_V2';
export const COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT0 =
  'COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT1 =
  'COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT2 =
  'COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT6 =
  'COPERNICUS_CLMS_LAI_GLOBAL_300M_10DAILY_V2_RT6';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT0 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT1 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT2 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT6 = 'COPERNICUS_CLMS_FAPAR_300M_10DAILY_V2_RT6';
export const COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT0 =
  'COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT1 =
  'COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT2 =
  'COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT6 =
  'COPERNICUS_CLMS_FCOVER_GLOBAL_300M_10DAILY_V2_RT6';
export const COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT0 =
  'COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT1 =
  'COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT2 =
  'COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT6 =
  'COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT6';
export const COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT0 =
  'COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT1 =
  'COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT2 =
  'COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT6 =
  'COPERNICUS_CLMS_GPP_GLOBAL_300M_10DAILY_V2_RT6';
export const COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT0 =
  'COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT1 =
  'COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT2 =
  'COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT6 =
  'COPERNICUS_CLMS_NPP_GLOBAL_300M_10DAILY_V2_RT6';
export const COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT0 =
  'COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT0';
export const COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT1 =
  'COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT1';
export const COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT2 =
  'COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT2';
export const COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT6 =
  'COPERNICUS_CLMS_GDMP_GLOBAL_300M_10DAILY_V2_RT6';

// --- CLMS Vector data ---

export const COPERNICUS_CLMS_UA_LCU_2018_VECTOR = 'UA_LCU_2018_VECTOR';
export const COPERNICUS_CLMS_UA_LCU_2018_RASTER = 'UA_LCU_2018_RASTER';
export const COPERNICUS_CLMS_UA_LCU_2021_VECTOR = 'UA_LCU_2021_VECTOR';
export const COPERNICUS_CLMS_UA_LCU_2021_RASTER = 'UA_LCU_2021_RASTER';
export const COPERNICUS_CLMS_UA_LCUC_2018_2021_VECTOR = 'UA_LCUC_2018-2021_VECTOR';
export const COPERNICUS_CLMS_UA_LCUC_2018_2021_RASTER = 'UA_LCUC_2018-2021_RASTER';
export const COPERNICUS_CLMS_UA_STL_2021_VECTOR = 'UA_STL_2021_VECTOR';
export const COPERNICUS_CLMS_UA_STL_2021_RASTER = 'UA_STL_2021_RASTER';

// --- Evoland ---

export const EVOLAND_C01_CONTINUOUS_FOREST_MONITORING = 'EVOLAND_C01_CONTINUOUS_FOREST_MONITORING';
export const EVOLAND_C02_FOREST_DISTURBANCE = 'EVOLAND_C02_FOREST_DISTURBANCE';
export const EVOLAND_C03_FOREST_BIOMASS = 'EVOLAND_C03_FOREST_BIOMASS';
export const EVOLAND_C04_COVER_CROP_TYPE = 'EVOLAND_C04_COVER_CROP_TYPE';
export const EVOLAND_C05_GRASSLAND_CROPLAND_GPP = 'EVOLAND_C05_GRASSLAND_CROPLAND_GPP';
export const EVOLAND_C06_SMALL_LANDSCAPE_FEATURES = 'EVOLAND_C06_SMALL_LANDSCAPE_FEATURES';
export const EVOLAND_C07_IMPROVED_WATER_BODIES_MAPPING = 'EVOLAND_C07_IMPROVED_WATER_BODIES_MAPPING';
export const EVOLAND_C08_CONTINUOUS_IMPERVIOUSNESS_MONITORING =
  'EVOLAND_C08_CONTINUOUS_IMPERVIOUSNESS_MONITORING';
export const EVOLAND_C09_AUTOMATED_LAND_USE_MAPPING = 'EVOLAND_C09_AUTOMATED_LAND_USE_MAPPING';
export const EVOLAND_C10_LAND_SURFACE_CHARACTERISTICS = 'EVOLAND_C10_LAND_SURFACE_CHARACTERISTICS';
export const EVOLAND_C11_ON_DEMAND_LAND_COVER_MAPPING = 'EVOLAND_C11_ON_DEMAND_LAND_COVER_MAPPING';
export const EVOLAND_C12_TREE_TYPES = 'EVOLAND_C12_TREE_TYPES';

// --- Orbit direction ---

export const ASCENDING = 'ASCENDING';
export const DESCENDING = 'DESCENDING';
